### ISSUE TITLE
LazyLoadEvent misleading type

### ISSUE THREAD

**Issue by yelhouti** [primefaces/primeng#10055]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

https://github.com/primefaces/primeng/blob/d38a70e6ad683e00ebc520c79d51623e69f279c4/src/app/components/api/lazyloadevent.ts#L10

Type seems to be wrong for filters, it should be FilterMetadata | FilterMetadata[]

due to the latest changes.

What do you think ?

**Comment by mylifeandcode** [comment]
I'd like to add to this discussion. We have a lot of code that was using LazyLoadEvents and setting filters based on table filters, like this, where _dtConjoinedConstraints_ is a Table:

` 
let event: LazyLoadEvent = {
       filters: this.dtConjoinedConstraints == undefined ? null : this.dtConjoinedConstraints.filters,
       //Snip, other code
};
`
But after upgrading to PrimeNG 11 (from version 9), this line gives the following error:

_Type '{ [s: string]: FilterMetadata | FilterMetadata[]; }' is not assignable to type '{ [s: string]: FilterMetadata; }'.
  Index signatures are incompatible.
    Type 'FilterMetadata | FilterMetadata[]' is not assignable to type 'FilterMetadata'.
      Type 'FilterMetadata[]' has no properties in common with type 'FilterMetadata'.ts(2322)
lazyloadevent.d.ts(9, 5): The expected type comes from property 'filters' which is declared here on type 'LazyLoadEvent'_

**Comment by m11t** [comment]
I also just ran into this inconsistent interface definition.
I have to agree with the motivation in #10269 and therefore hope to take this into consideration:

> Angular is moving towards strict, and it is hard to impossible to pass strict when the output does not match the interface declarations.

**Comment by m11t** [comment]
There is actually already a pull request for this: #10337

**Comment by PHuhn** [comment]
I'm the author of [10269](https://github.com/primefaces/primeng/issues/10269).  We are now in version 13, what is going to happen with this issue?

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by lwestfall** [comment]
Can we get this reopened? This still isn't fixed. Feels like low hanging fruit too.

**Comment by HussainAbuHajjaj993** [comment]
Hello, 
I Have the same issue it works in some components and not in others, it starts to be a headache,  
 Type 'Event' has no properties in common with type 'LazyLoadEvent'.

``        (LazyLoadEvent)="loadDonors($event)"
                                       ~~~~~~

  src/app/area/donation/receipts/receipts.component.ts:9:16
    9   templateUrl: './receipts.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component ReceiptsComponent.
``

Kindly provide the solution I've been stuck on this for a week.

**Comment by lwestfall** [comment]
If this is breaking your CI/CD (like it is for me), you can run this Powershell (save it to a .ps1 file in your root directory) to patch the declaration to make the compiler happy. I don't have bash version for my *nix friends but it would be pretty easy to translate.

```ps1
################################################################
#   Fix LazyLoadEvent filters property type declaration
#   See https://github.com/primefaces/primeng/issues/10055
################################################################

$lazyLoadEventFile = Get-ChildItem node_modules/primeng/api/lazyloadevent.d.ts
$content = Get-Content $lazyLoadEventFile -Raw
$content = $content -replace "\[s: string\]: FilterMetadata;", "[s: string]: FilterMetadata[];"
Write-Output $content | Out-File -FilePath $lazyLoadEventFile -encoding utf8
```

**Comment by cetincakiroglu** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

**Comment by ivan-price-acted** [comment]
> Hi,
> 
> The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

@cetincakiroglu just letting you know that this is still an issue with PrimeNG 17.12.0 .. this issue shouldn't be closed :)

**Comment by PHuhn** [comment]
The fix was confusing to me because you created a new import and kept the original.  I've updated my code and removed my fixes.

**Comment by ivan-price-acted** [comment]
@PHuhn  can you elaborate ? are you implying there is an alternative interface to import that lists the `filters` property as an array, not a dict ?

**Comment by PHuhn** [comment]
The original import was **LazyLoadEvent**.  The new and improved import is **LazyLoadMeta**.
