### ISSUE TITLE
Frozen columns with flexible viewport 

### ISSUE THREAD

**Issue by andreihaiducu** [primefaces/primeng#10584]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

https://stackblitz.com/edit/primeng-tablescroll-demo-lvl8y9

**Current behavior**
When placing table inside of a resizable viewport if you add frozen columns to the table and resize the viewport, at some point the frozen column will scroll with the other columns

**Expected behavior**
Frozen column should stay in place until last scrollable column is shown.

**Minimal reproduction of the problem with instructions**
Works with the default stackblitz example. 

**Please tell us about your environment:** MacOS

* **Angular version:** 12.1.4

* **PrimeNG version:** 12.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by yigitfindikli** [comment]
Fixed in v12.1.0.

https://stackblitz.com/edit/primeng-tablescroll-demo-4wkcxz

**Comment by andreihaiducu** [comment]
Not sure if I'm checking in the right way, but event in your stackblitz example I can see the issue.

Steps:
1. Press View Button from Flexible viewport section.
2. Scroll left and the Name column will scroll when Company column appears. 

Thanks for quick response.

**Comment by dragosheroiu95** [comment]
> Not sure if I'm checking in the right way, but event in your stackblitz example I can see the issue.
> 
> Steps:
> 
> 1. Press View Button from Flexible viewport section.
> 2. Scroll left and the Name column will scroll when Company column appears.
> 
> Thanks for quick response.

Yes I can confirm that this is still happening. Any solution so far?

**Comment by jaredmartinez** [comment]
If you add a 2nd frozen column it is the same issue, and the 2nd column does not actually freeze. Only in flexible viewports.

**Comment by andreihaiducu** [comment]
@yigitfindikli any news on this? is there anything that we are doing wrong ?
