### ISSUE TITLE
p-dropdown blank entry compressed

### ISSUE THREAD

**Issue by kt215** [primefaces/primeng#1107]
When a p-dropdown entry label is blank (empty string) it appears vertically compressed:

![image](https://cloud.githubusercontent.com/assets/14261464/19620467/2ad8bbda-983b-11e6-8771-35c436543d00.png)

It should have the same height as the rest of the entries.

Using PrimeNG 1.0.0 Beta 19, Omega Theme, and Chrome 53.0.2785.143

**Comment by kt215** [comment]
I "fixed" this by adding itemHeight field to Dropdown in dropdown.d.ts, and in dropdown.js defaulting the value to 20px and adding `[style.min-height]=\"itemHeight||'auto'\"` to #item li-tag.

Is this a valid enhancement or should this be fixed in dropdown.css somehow?

**Comment by 4kochi** [comment]
Will this be fixed in the future in the control itself? Or do one have to use the css workaround?

**Comment by kt215** [comment]
From what I can see, it looks like @upmauro 's fix is scheduled to be merged in with release 1.2

**Comment by upmauro** [comment]
@cagataycivici this issue is already fixed and we can close.

**Comment by kt215** [comment]
I still had to apply the same style fix to dropdown.js for PrimeNG 4.0.3 to prevent collapse, so I'm not convinced this is fixed yet :-)

**Comment by leye0** [comment]
Not fixed.

**Comment by dmoore1181** [comment]
I am still having this same issue with priming version 7.1.3. Basically if you didn't know it was there, you would never even notice it. I am using this to be able to filter by users, so I want my users to be able to turn the filter off by simply selecting the blank option. For now I will change this to ALL to simplify the matter.
