### ISSUE TITLE
Dropdown virtualScroll filter bug

### ISSUE THREAD

**Issue by umuero** [primefaces/primeng#12461]
### Describe the bug

p-scroller doesn't update the initial scroll after filter changes,
scroll height fixes itself after p-scroller.onScrollChange is called
14.1.1 works correctly, bug is introduced in 14.2.0, still active in 15.0.1

<img width="277" alt="image" src="https://user-images.githubusercontent.com/1029173/210769682-bbc578bb-6ed7-43da-82e5-b2a894307ad3.png">

https://stackblitz.com/edit/primeng-dropdown-demo-jvprrv

### Environment

primeng: 15.0.1
angular 15.0.4

### Reproducer

https://stackblitz.com/edit/primeng-dropdown-demo-jvprrv?file=package.json

### Angular version

15.0.4

### PrimeNG version

15.0.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/primeng-dropdown-demo-jvprrv?file=package.json
2. Filter for "8"
3. The result preview is empty, it corrects itself after scrolling
4. p-scroller > div > ul has style: "translate3d(0px, 32675px, 0px)", it should be 0,

**Comment by bhavesh2777** [comment]
Hello @umuero ,

For some reason the stackblitz demo was not working also I tried looking into the component directly but was unable to reproduce the issue. I tried to enable Ivy from settings but still no luck.
![Capture](https://user-images.githubusercontent.com/52625842/210850981-9acec0cc-e667-47cb-8f75-9ebeed2f3ef9.PNG)

**Comment by cetincakiroglu** [comment]
Hi @umuero,

This issue is fixed by https://github.com/primefaces/primeng/commit/b218f47b029fd6b63982f2078715657a968cdf95
Closing the issue, thanks for your report and support!

**Comment by sak963** [comment]
Hi @cetincakiroglu 
thanks for the help,  but it still doesn't work in "primeng": "15.1.0"

![image](https://user-images.githubusercontent.com/41641650/213468615-c0066b2f-6904-4253-96c9-c1c196165915.png)

thanks for your support

**Comment by cetincakiroglu** [comment]
Hi,

A refactored and working version of your example: https://stackblitz.com/edit/primeng-dropdown-demo-mezh18?file=src%2Fapp%2Fapp.component.html

**Comment by sak963** [comment]
Hi @cetincakiroglu , thanks for the quick response.
for the bug to be replicated
[(ngModel)]="item" must have value and the selector appears with an initial load and then you look for the 8

I modified your fork to replicate

https://stackblitz.com/edit/primeng-dropdown-demo-pdztth?file=src%2Fapp%2Fapp.component.html

**Comment by durmishie** [comment]
Hello, I'm encountering the same bug in:

1. Angular: 14.0.1 
2. Primeng: 14.1.2

I know it's fixed in the 15.1.x version of the Primeng, but I cannot update the packages at the moment. Is there "hack" to correct the behaviour of the dropdown, or updating to the latest version of the Primeng is the only solution?

**Comment by achrafha** [comment]
Hello, I'm still having the same issue : 
- Angular : 15.2.5
- PrimeNg : 15.3.0
The example given by [sak963] still contain the same issue. Can you please reopen this issue ?

**Comment by growms** [comment]
I'm blocked in 14 too and it seems to be fixed by : 

```html
<p-dropdown
  #myDD
  [virtualScroll]="true"
  [virtualScrollItemSize]="30"
  (onFilter)="onDDFilter(myDD)"
  ...
></p-dropdown>
```

in the same component :
```ts
 onDDFilter(dd:DropDown) {
    if (dd.scroller) {
      dd.scroller.contentEl.style.transform = 'translate3d(0px, 0px, 0px)';
    }
  }
```
