### ISSUE TITLE
Galleria: this.galleria is undefined

### ISSUE THREAD

**Issue by ruskovweb** [primefaces/primeng#13094]
### Describe the bug

I am using custom content for my galleria. When I try to open an image it throws an error `this.galleria is undefined`.

### Environment

Node v18.12.1

### Angular version

16.0.2

### PrimeNG version

^16.0.0-rc.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Browser(s)

Firefox

### Steps to reproduce the behavior

```html
<p-galleria
    [value]="servicePhotos"
    [(visible)]="displayCustom"
    [(activeIndex)]="activeIndex"
    [responsiveOptions]="responsiveOptions"
    [containerStyle]="{ 'max-width': '1440px' }"
    [numVisible]="7"
    [circular]="true"
    [autofocus]="true"
    [fullScreen]="true"
    [showItemNavigators]="true"
    [showThumbnails]="false"
  >
      <ng-template pTemplate="item" let-item>
        <img [src]="item.url" style="width: 100%; display: block" />
      </ng-template>
</p-galleria>
```

### Expected behavior

To not throw an error.

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/pull/13095

**Comment by ruskovweb** [comment]
Great, thank you!

**Comment by brandon-philpot** [comment]
> fixed in #13095

What version will the fix become available? I currently am running 16.0.2 and it is still broken. Also what time frame are we working with until release?
