### ISSUE TITLE
Galleria | cannot read properties of undefined error

### ISSUE THREAD

**Issue by cetincakiroglu** [primefaces/primeng#13124]
https://github.com/primefaces/primeng/blob/master/src/app/components/galleria/galleria.ts#L457

**Comment by w1andresv** [comment]
<img width="629" alt="Screenshot 2023-06-07 at 15 25 54" src="https://github.com/primefaces/primeng/assets/11529941/1f7a55cc-3ed3-4506-a64a-11ea11bc5211">
I'm use primeng v16 and i have this is the error on gallery component

**Comment by funiok** [comment]
Exact same problem here! Using `angular ^16.0.0` with `primeng ^16.0.0-rc.1`. Afaics the latest `16.0.0-rc.2` does not include any fix.

**Comment by timkrysta** [comment]
bump

**Comment by ynixt** [comment]
The problem still happen at `primeng": "^16.0.0`

**Comment by cetincakiroglu** [comment]
Fixed in https://github.com/primefaces/primeng/pull/13095/files

**Comment by barais** [comment]
Dear @cetincakiroglu 
I am not a fan of the proposed patch, 
typescript has changed its semantics for instantiating class parameters (set properties before calling the constructor). So there will also be a problem for the differ attribute part (line 470 same file) . 

It would be better to instantiate these properties in the constructor as proposed here. https://github.com/primefaces/primeng/pull/13206/files

What do you think?

**Comment by brandon-philpot** [comment]
im using version 16.0.2 and this is still broken. When will the fix be available for latest version.? @cetincakiroglu

**Comment by brandon-philpot** [comment]
everything seems to be good in 16.1.0
