### ISSUE TITLE
Installing Primeng 16 on Angular 16 Fails

### ISSUE THREAD

**Issue by kiranatious** [primefaces/primeng#13211]
### Describe the bug

**I'm using angular 16**
below is my decencies 
`"dependencies": {
    "@angular/animations": "^16.0.0",
    "@angular/common": "^16.0.0",
    "@angular/compiler": "^16.0.0",
    "@angular/core": "^16.0.0",
    "@angular/forms": "^16.0.0",
    "@angular/platform-browser": "^16.0.0",
    "@angular/platform-browser-dynamic": "^16.0.0",
    "@angular/router": "^16.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.0.5",
    "@angular/cli": "~16.0.5",
    "@angular/compiler-cli": "^16.0.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~5.0.2"
  }`

when i install Primeng i get the below errors
i tried with npm i primeng@16.0.0  , npm i primeng@16.0.0-rc.2 , npm i primeng@16.0.0-rc.1

`pm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: angular1605project@0.0.0
npm ERR! Found: @angular/core@16.1.1
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"16.1.1" from @angular/animations@16.1.1
npm ERR!   node_modules/@angular/animations
npm ERR!     peerOptional @angular/animations@"16.1.1" from @angular/platform-browser@16.1.1
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"16.1.1" from @angular/forms@16.1.1
npm ERR!       node_modules/@angular/forms
npm ERR!         @angular/forms@"^16.0.0" from the root project
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     @angular/animations@"^16.0.0" from the root project
npm ERR!   peer @angular/core@"16.1.1" from @angular/common@16.1.1
npm ERR!   node_modules/@angular/common
npm ERR!     peer @angular/common@"16.1.1" from @angular/forms@16.1.1
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"^16.0.0" from the root project
npm ERR!     peer @angular/common@"16.1.1" from @angular/platform-browser@16.1.1
npm ERR!     node_modules/@angular/platform-browser
npm ERR!       peer @angular/platform-browser@"16.1.1" from @angular/forms@16.1.1
npm ERR!       node_modules/@angular/forms
npm ERR!         @angular/forms@"^16.0.0" from the root project
npm ERR!       3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!     3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!   6 more (@angular/compiler, @angular/forms, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! primeng@"16.0.0-rc.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/core@16.0.6
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"~16.0.0" from primeng@16.0.0-rc.1
npm ERR!   node_modules/primeng
npm ERR!     primeng@"16.0.0-rc.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/kiran/.npm/_logs/2023-06-16T08_41_41_395Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/kiran/.npm/_logs/2023-06-16T08_41_41_395Z-debug-0.log`

### Environment

Local Setup, Mac OS
Angular CLI: 16

### Angular version

16.0.0

### PrimeNG version

16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.0

### Browser(s)

Chrome

**Comment by rauu** [comment]
Same thing happens with me

**Comment by igordanilovski** [comment]
They made pull request #13203 that should fix this but still doesn't work for me...

**Comment by Menecats** [comment]
As a workaround you can explicitly install angular version `16.0.x` by changing the version definitions in the `package.json` file from `"^16.0.0"` (which installs angular `16.1.1` as the moment of writing this comment) to `"~16.0.0"` (which installs angular `16.0.6` as of the moment of writing this comment)

**Comment by igordanilovski** [comment]
Can try right now, but still that is not solution, also you can try with npm install --force I think it works for me, they just need to fix thix. There was previously another issue but they closed it and merged the pull request but the issue is still there.

**Comment by igordanilovski** [comment]
16.0.1 fix this issue.

**Comment by kiranatious** [comment]
following @Menecats  advice it worked .. however on ng serve it started throwing the below Error
./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Cannot resolve type entity SafeHtmlPipe to symbol

Error: node_modules/primeng/menu/menu.d.ts:139:100 - error TS2304: Cannot find name 'SafeHtmlPipe'.

139     static ɵmod: i0.ɵɵNgModuleDeclaration<MenuModule, [typeof Menu, typeof MenuItemContent, typeof SafeHtmlPipe], [typeof i1.CommonModule, typeof i2.RouterModule, typeof i3.RippleModule, typeof i4.TooltipModule], [typeof Menu, typeof i2.RouterModule, typeof i4.TooltipModule]>;
                                                                                                       ~~~~~~~~~~~~

**Comment by kiranatious** [comment]
looks like Primeng works stable with only Angular 15

**Comment by cretara** [comment]
Fixed by [PrimeNG v.16.0.1](https://github.com/primefaces/primeng/releases/tag/16.0.1)

**Comment by faileon** [comment]
Still broken on PrimeNG v16.0.1 with Angular 16.1.0

Compiler throws `Error: Cannot resolve type entity SafeHtmlPipe to symbol` when working with [MenuModule](https://github.com/primefaces/primeng/blob/264f694e1f706f5157d6cea080a2248e0e33d7b9/src/app/components/menu/menu.ts)
