### ISSUE TITLE
Table columns change size if other columns are resized (expand mode)

### ISSUE THREAD

**Issue by micw** [primefaces/primeng#13214]
### Describe the bug

On a table with expand mode, when I change the size of a table column, other columns change their size too (very good visible if you resize the 2nd column - then the 1st column and probably the others too increase the size slightly).

### Environment

Angular and PrimeNG 15. Also reproducible on the latest demo page (including Primeng 16)

### Reproducer

https://primeng.org/table#expand-mode

### Angular version

15

### PrimeNG version

15.4.3 TLS, also in 16.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v20.3.0

### Browser(s)

Firefox

### Steps to reproduce the behavior

1. Go to https://primeng.org/table#expand-mode
2. Increase or decrease the size of the column "Name"
3. Watch the size of the column "Code" - it changes

### Expected behavior

Code should not alter it's size since it's not touched by the user

**Comment by micw** [comment]
Possibly the same (but closed without a fix): https://github.com/primefaces/primeng/issues/11186

**Comment by nicholas-ochoa** [comment]
@micw I submitted a pull a few months ago with a fix for this, but it has not been accepted. #12529

**Comment by damianpolak** [comment]
I've got this same bug. I'm still waiting for fix...

**Comment by sriteja2602** [comment]
Hi! This is fixed in v16 and above.

**Comment by NynaPykulska** [comment]
OP mentioned that it still happens in v16. I am also experiencing this problem in 16.9.1. To me, it happens for a table with a footer. When I remove the footer, resize works as expected.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
