### ISSUE TITLE
Toasts with custom keys overlap

### ISSUE THREAD

**Issue by eukuz** [primefaces/primeng#13290]
### Describe the bug

When creating toasts with different keys, they overlap eachother and toasts without keys!
As @OliverDH in https://github.com/primefaces/primeng/issues/11366#issuecomment-1209452861 said:
> Hi, I think the problem is to use different keys for the toast. The initial project modified to show the problem: https://stackblitz.com/edit/github-1metrx-yhbjas?file=src/app/app.component.ts

### Environment

Windows 10
Chrome

### Reproducer

https://stackblitz.com/edit/github-1metrx-yhbjas?file=src/app/app.component.ts

### Angular version

15.0.5

### PrimeNG version

14.2.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Browser(s)

Chrome

### Steps to reproduce the behavior

1. Create toasts with different keys, and toasts without keys just like in https://stackblitz.com/edit/github-1metrx-yhbjas?file=src/app/app.component.ts
2. Show several toasts
3. See toasts overlap

### Expected behavior

1. Create toasts with different keys, and toasts without keys just like in https://stackblitz.com/edit/github-1metrx-yhbjas?file=src/app/app.component.ts
2. Show several toasts
3. See toasts stack up and don't overlap eachother

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

**Comment by jvegaseg** [comment]
This issue persist in latest versions (**custom toast messages with same key are not stacked, are overlapped** ):

Angular version:
17.0.8

PrimeNG version
17.3.1 

For stackblitz example, you can use same reported with this issue updating dependencies.

**Comment by jacks-bush** [comment]
I would also like to see if there is a solution for this.
