### ISSUE TITLE
DataTable rowExpansion bug with Angular 2.2

### ISSUE THREAD

**Issue by ribizli** [primefaces/primeng#1366]
Hi, I've reported this bug on angular's github, but I'd like to submit it here too, that you can be aware of it: https://github.com/angular/angular/issues/12968

**Comment by bogacg** [comment]
Similar to #1346

**Comment by ribizli** [comment]
I've reproduced the issue outside PrimeNG, and also found a workaround: reference the row expansion template in DataTable either by a directive or by name.
Actually I've already added an issue about this long time ago: #966

**Comment by ribizli** [comment]
Guys! I just warn you, the fix of this and #966 might be a future breaking change if you do after final release.

**Comment by cagataycivici** [comment]
Fixed via #1396

**Comment by ribizli** [comment]
It's still not working: http://embed.plnkr.co/bJ0ln941VPbUX7KP3Mtk/
From the 2nd opening it messes up the template variables.
I don't say, that this is not an angular issue, but can be avoided when not using `TemplateRef` but some more specific.

**Comment by bogacg** [comment]
I still have same problem even after upgrading to PrimeNG 1.0.0

**Comment by ribizli** [comment]
I've opened a new issue for this.

**Comment by bogacg** [comment]
Ok, I've narrowed down to this:
IF I remove *ngFor I have inside template area (for an array property I have in each row element) I don't have any problems. As soon as I introduce that, expander messes up.

**Comment by ribizli** [comment]
I've figured this out already, mentioned in every issue I've created.
