### ISSUE TITLE
Menu/TieredMenu: First Element focussed when opening by button trigger

### ISSUE THREAD

**Issue by skappler** [primefaces/primeng#13818]
### Describe the bug

When opening a Menu or TieredMenu, the first menu entry automatically has the p-focused class with the corresponding styling.

![Screenshot 2023-10-06 at 14 38 37](https://github.com/primefaces/primeng/assets/2983995/21b454d0-11a8-4c21-b22d-ef130485124c)

### Environment

Angular 16 app. Can also be reproduced on the demo page of primeng

### Angular version

16.2.8

### PrimeNG version

16.3.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.20.1

### Browser(s)

Chrome 117, Firefox 118

### Steps to reproduce the behavior

1. Go to [https://primeng.org/tieredmenu](https://primeng.org/tieredmenu)
2. Click the Show button in the popup section
3. Observe the first entry being highlighted

### Expected behavior

The first entry should not be highlighted

**Comment by scurk1415** [comment]
Would be nice to have this fixed

**Comment by bootsie123** [comment]
I'm running into this with the menu component on PrimeNG `17.0.0-beta.1`. A fix would also be greatly appreciated. Thanks!

**Comment by Halynsky** [comment]
So small issue, but it's really confusing the users. Any updates?

**Comment by skappler** [comment]
Ich looked at the primeng codebase and found some code that specifically enables this behaviour, so I assume this might be a feature not a bug. However, I don't really understand it from a UI perspective, so maybe someone from the team can at least explain it?

**Comment by jermylucas** [comment]
@skappler @Halynsky This bug should have been fixed in the 17 rc. If you can give that a try and check. It's no longer happening on the primeng.org site either

**Comment by skappler** [comment]
Can't confirm this. For me it's still happening on the primeng.org site when selecting version 17.1.0

**Comment by Halynsky** [comment]
@jermylucas Thx for response and for the try, but unfortunately it not work on priming.org with selected 17.3.0 (latest) version. Are you sure that it's already used on the priming.org? Is this fix released in the 17.3.0? Maybe now we can try to check it in the apps?

![image](https://github.com/primefaces/primeng/assets/8502557/84a3ba6d-acd6-47d3-afa0-efa96aa3c1e5)

**Comment by STotev** [comment]
I can confirm it's still an issue in 17.3.3.

**Comment by jesuspa17** [comment]
Any update?

**Comment by rtv10dev** [comment]
> Any update?

It looks like it is still happening

**Comment by pablodmngz98** [comment]
It would be nice if this could be fixed

**Comment by aaron-everly** [comment]
This would be a nice small fix. It is confusing, especially for menus with 2 items. Hovering the next item in the list makes both look active.

**Comment by PacoMPerez** [comment]
I'm facing the same issue, while PrimeNG fix this at some point I have this workaround:

![Captura desde 2024-02-20 18-00-35](https://github.com/primefaces/primeng/assets/32292841/a1ee06e2-da3f-484d-83ec-88577486e470)

I've added this to `_tieredmenu.scss`, basically I'm  overwritting the background set on `_mixins.scss` for the focus on menuitems.

**Comment by mscharrig** [comment]
Please fix this problem, it is extremely annoying. Or at least give us a way to control the focus behavior.

**Comment by dalenguyen** [comment]
I created fix for this one. Let's wait for feedback from team :)
