### ISSUE TITLE
Component: Autocomplete with virtual scroll, display list broken

### ISSUE THREAD

**Issue by ItachiPM** [primefaces/primeng#13997]
### Describe the bug

Hello

I have encountered the issue with autocomplete component. The problem is with scrolling list of item in component, the list display is broken.

Application:

![autocomplete-virtualscroll1](https://github.com/primefaces/primeng/assets/104820352/4585aca6-0d48-4cba-80cc-dc0481dc477b)

Demo (https://www.primefaces.org/primeng-v15-lts/autocomplete#virtualscroll):

![autocomplete-virtualscroll2](https://github.com/primefaces/primeng/assets/104820352/c9e516a2-9cd8-4d7e-b7ac-28c762f9b218)

### Environment

https://www.primefaces.org/primeng-v15-lts/autocomplete#virtualscroll

### Reproducer

https://stackblitz.com/run?file=src%2Findex.html,src%2Fenvironments%2Fenvironment.ts,src%2Fapp%2Fdemo%2Fautocomplete-virtual-scroll-demo.html

### Angular version

15.2.6

### PrimeNG version

15.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.14.1

### Steps to reproduce the behavior

follow the steps for gif

**Comment by cetincakiroglu** [comment]
Hi,

The version you use is outdated and will not receive an update unless you're not an LTS user. We've already fixed the issue and it doesn't exist in v16. Please use newer versions.

If you're an LTS owner, please open a ticket on PRO platform.

Closing the issue since it's already fixed and not exist in latest version

**Comment by ItachiPM** [comment]
Hi, 

In version v16 the problem still exist. Please look on the gif below:

![autocomplete-virtualscrollv16](https://github.com/primefaces/primeng/assets/104820352/a3f078dd-1c56-41c4-94a3-b43685a943b5)

**Comment by bmajkut** [comment]
@cetincakiroglu issue is still visible in v16 version. Please reopen the ticket.

**Comment by RajeshCh17** [comment]
yes, seems to be after clearing input text it doesnot show suggestions again....
