### ISSUE TITLE
Component: p-dropdwon onChange is called multiple times at init

### ISSUE THREAD

**Issue by stephanebouget** [primefaces/primeng#14005]
**At launch, (onChange) callback is called 3 times since the 16.7.0**

Can be tested here:
https://stackblitz.com/edit/zy6kzt?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html
![image](https://github.com/primefaces/primeng/assets/13203455/cda919e5-5878-42ad-ac1c-98a4be79b93c)

On previous versions, onChange is not called at init:
https://stackblitz.com/edit/styezg?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts,src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html

### Environment

Primeng 16.7.0
Angular 16

### Angular version

16.2.0

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18

### Steps to reproduce the behavior

just add the dropdonw component into a page

**Comment by cetincakiroglu** [comment]
Hi,

With version 16.7.0, we have released the first part of the accessibility implementation for inputs that we have been working on for a long time. Based on the research we conducted during the implementation, we decided that many components needed changes in their structure and simplification, and these components were rewritten. Unfortunately, after extensive testing, there may be unexpected and unforeseen bugs that have emerged. We are grateful for your reports, and we are working to address them in the upcoming release!

**Comment by ElHabb** [comment]
I'm still having the same issue in version 16.7.1. In which release will it be fixed?

**Comment by stephanebouget** [comment]
Indeed it's not fixed in 16.7.1 : 
![image](https://github.com/primefaces/primeng/assets/13203455/30c2a9bc-5ac1-46ad-bc56-c8ef61180496)

test here : https://stackblitz.com/edit/zy6kzt-adg7k5?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts,package.json

@cetincakiroglu can you re-open the issue ?

**Comment by tmc101** [comment]
I'm still seeing this in p-dropdown for 16.7.1.

Plus other issues such as:

1. The dropdown is being set to dirty when its value is changed programmatically - which is not the expected behaviour.
2. When an item is selected, the dropdown displays the value instead of the label.

From PrimeNg 16.0.2 to 16.7.2 there has been a huge refactoring of the dropdown component, followed by multiple bugfix attempts, but there are zero new unit tests in dropdown.spec.ts.

**Comment by pete-mcwilliams** [comment]
I'm also experiencing issues with change of functionality between 16.5 to 16.7.2,  I have my own input components that utilise  NG_VALUE_ACCESSOR wrapping ng prime inputs I am passing the onChanges up using (onChanges)=onChanges(value) because the onChanges is triggered on writevalue in new version of primeng angular has not had a chance to register my onChanges function on my component through it's standard NG_VALUE_ACCESSOR.  

@cetincakiroglu please reopen the issue

**Comment by roberttuttle** [comment]
Issue still a problem with 16.7.2 release. p-dropdown still emits multiple "empty" onChange events during init bouncing between value being null / undefined. The current "fix" code only checks for a delta in the value and of course null != undefined.

**Comment by eXpertise7** [comment]
Confirming the issue on primeng@16.7.2.

**Comment by stephanebouget** [comment]
tested OK in 16.8.0 : https://stackblitz.com/edit/zy6kzt-p13lbv?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts,package.json

**Comment by OleksiiPrykhodko** [comment]
Issue still a problem with 18.0.0-beta.2
