### ISSUE TITLE
Dropdown filtering issues with array of strings

### ISSUE THREAD

**Issue by Hambardzum93** [primefaces/primeng#14011]
### Describe the bug

The dropdown filtering with array of strings works incorrectly. I have the dropdown like this.

![MicrosoftTeams-image (7)](https://github.com/primefaces/primeng/assets/71258675/3ae289c2-b2b9-4e1d-9e12-b394cbcff19b)

_**Bug 1: The empty text doesn't show when no data is found.**_

![MicrosoftTeams-image (8)](https://github.com/primefaces/primeng/assets/71258675/0d89186e-0950-41f0-aec2-78726434f2f1)

_**Bug 2:The filtering totally doesn't work with string array**_

![MicrosoftTeams-image (9)](https://github.com/primefaces/primeng/assets/71258675/77c99486-07ac-41be-ada4-3cd0fbb8daca)

_**Bug 3: After clear get "[object PointerEvent]" as value**_

![MicrosoftTeams-image (10)](https://github.com/primefaces/primeng/assets/71258675/4915e819-601e-4076-9931-301fc6f99ad9)

### Environment

Angular: 16.2.7
PrimeNG: 16.7.0
Browser: Chrome (Latest)

### Angular version

16.2.7

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

**Comment by samvel077** [comment]
Also found it

**Comment by Yedigaryan** [comment]
Yeah , the same issue here!

**Comment by K-Makaryan** [comment]
Same issue after last update.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks a lot for reporting the issue, could you please also share a stackblitz example so we can identify the root cause clearly?

**Comment by Hambardzum93** [comment]
@cetincakiroglu 
https://stackblitz.com/edit/2q7jhl?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html,src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

**Comment by cetincakiroglu** [comment]
> @cetincakiroglu https://stackblitz.com/edit/2q7jhl?file=src%2Fapp%2Fdemo%2Fdropdown-basic-demo.html,src%2Fapp%2Fdemo%2Fdropdown-basic-demo.ts

Thanks a lot for the example!

**Comment by cetincakiroglu** [comment]
Hi everyone,

With version 16.7.0, we have released the first part of the accessibility implementation for inputs that we have been working on for a long time. Based on the research we conducted during the implementation, we decided that many components needed changes in their structure and simplification, and these components were rewritten. Unfortunately, after extensive testing, there may be unexpected and unforeseen bugs that have emerged. We are grateful for your reports, and we are working to address them in the upcoming release!

**Comment by mcrtricolor** [comment]
Hi. I'm still having problems with the dropdown filter in versions bigger than 16.6.0.

I get the error 'TypeError: option.indexOf is not a function' in file 'node_modules/primeng/fesm2022/primeng-dropdown.mjs' every time i filter. This is happening with at least versions 16.9.1 and 17.

I had to downgrade to 16.6.0 even though i'm using angular 17.

The Multiselect filter is also not working properly.
