### ISSUE TITLE
Dropdown Option: Does not display selected value when editable=true

### ISSUE THREAD

**Issue by Triskae** [primefaces/primeng#14216]
### Describe the bug

When using Dropdown options component, with editable=true, the selected option is not displayed and even, if an initial value is provided, it also does not display it.

### Environment

"@angular/cdk": "^17.0.1",
"@angular/common": "^17.0.3",
"@angular/compiler": "^17.0.3",
"@angular/core": "^17.0.3",
"@angular/fire": "^16.0.0",
"@angular/forms": "^17.0.3",
"primeng": "^16.9.1",

### Reproducer

https://stackblitz.com/edit/j4pc5m?file=src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.html,src%2Fapp%2Fdemo%2Fdropdown-reactive-forms-demo.ts

### Angular version

17.0.3

### PrimeNG version

16.9.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.2.0

### Steps to reproduce the behavior

Use DropdownOption component, set the param editable to true.

**Comment by cetincakiroglu** [comment]
Hi,

Could you please try with it PrimeNG 17.0.0-beta.1 I couldn't replicate with the latest. Probably the issue is fixed in 16.9.2

**Comment by Triskae** [comment]
In the provided stackblitz, it uses the v17 version of primeng, and the problem is still there.

**Comment by Triskae** [comment]
https://github.com/primefaces/primeng/assets/28785555/20c7f4df-41c6-4220-903b-63ca57b33155

**Comment by Triskae** [comment]
I have a little more data about this bug. It only happens when you set editable to true, and you set optionValue to some value. If there's not optionValue, there's no problem.
The problem is that it's a regression, because, I also use Reactive forms with your components, and in order to store the proper selected data, I have to specify the optionValue option, to not store the whole object in the form.

The options we give to this component have to following structure: 
```typescript
export interface DropdownOption<T> {
  label: string;
  value: T;
  disabled?: boolean;
  tooltip?: string;
  dataKey?: string;
}
```

So we **MUST** use optionValue, in order to not have a FormControl with this object in it, instead of only the "value" field.

**Comment by Triskae** [comment]
Cannot even use the selectedItem template to bypass the problem. Everything seems linked to editable=true. I updated the stackblitz to illustrate the problem

**Comment by Triskae** [comment]
For those using an option objet with that looks like this: 
```export interface DropdownOption<T> {
  label: string;
  value: T;
}```

You can omit optionValue and optionLabel property, and it will solve the problème . 
If your options objects do not use an object like the above one, you will have to wait the bugfix sorry.

**Comment by shawnweeks** [comment]
@Triskae I just ran into this today and the workaround above still has a bug. After selecting an option `value` is displayed instead of `label`.

**Comment by Triskae** [comment]
Any news guys ? @cetincakiroglu

**Comment by dalenguyen** [comment]
Try with v17.10.0, it seems working now.

**Comment by Alexkill536ITA** [comment]
I have also encountered this bug also occurs with **filter** option instead of editable

PrimeNg: 17.18.3

**Comment by tipodisimmia** [comment]
Same problem for me with filter option instead of editable!!!

PrimeNg: 17.18.3

**Comment by cnlane** [comment]
I'm having the same problem using PrimeNg: 17.18.11 and NOT using the filter or editable options but I am using [(ngModel)] (template driven).  In another application, I'm using formControlName (reactive) instead.  Not sure if that's the difference but maybe?

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
