### ISSUE TITLE
MenuItem: Update of  'expanded' and 'label' properties not working

### ISSUE THREAD

**Issue by marcioluish** [primefaces/primeng#14893]
### Describe the bug

The following issue was opened in 12/11/2023 and closed in 12/13/2023, having the fix being checked in v17.1.0.

https://github.com/primefaces/primeng/issues/14329

I honestly didn't follow up PanelMenu's new releases, but in v17.1.0 the issue was only partially fixed and now in v17.8.0, we have the same behavior as in versions above v16.0.2.

Below you can find 2 GIFs comparing v16.0.2 and v17.8.0. In these I access sub-menu items and change their `label` and `expanded` properties by clicking in the `Change` button.

Here's the link to Stackblitz using v16.0.2: https://stackblitz.com/edit/gegncb?embed=1&file=package.json

### v16.0.2
![Primeng_16_0_2](https://github.com/primefaces/primeng/assets/60225443/543d0bcd-c8f5-41e0-b54f-80e4a7afaf15)

### v17.8.0
![Primeng_17_8_0](https://github.com/primefaces/primeng/assets/60225443/a05a1c7c-084f-4b00-b5df-b3efdad0e340)

### Environment

Angular 17.2.1 so as PrimeNg 17.8.0

### Reproducer

https://stackblitz.com/edit/4sbrb2-gkf3lq?file=src%2Fapp%2Fdemo%2Fpanel-menu-multiple-demo.ts

### Angular version

17.2.1

### PrimeNG version

17.8.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

**Comment by psarno** [comment]
I attempted to update PrimeNG to 17.11 and it caused a major regression in behavior of the `<p-panelMenu>`.

When expanding a node, it seems to briefly expand all of the children under that node before immediately collapsing them.  When you go to collapse the parent, the same process occurs, where it expands and then collapses the children before collapsing the parent.

I backed it down again to 17.8 and everything is working as normal.

We aren't doing anything fancy with the menu as far as I can tell.  We set the `expanded` property on parent nodes based on whether or not the children are selected, which is based on the route.  This keeps the menus expanded properly when the page is refreshed. i.e.

`expanded: this.router.url.includes('/some/route')`

That's about it.  But it was unusable in 17.11.  I don't know if this is the specific commit that is causing us problems, but it does deal with `MenuItem` and `expanded`.

**Comment by marciohamasaki** [comment]
@cetincakiroglu the chagen/fix is not working for me as well.
Please refer to below GIF taken from stackblitz of PanelMenu primeng official website:

PNG
![primeng_17_11](https://github.com/primefaces/primeng/assets/162062584/2fb7241d-fbc4-45d0-b251-7ffdc9ef9edf)

Stackblitz Link
https://stackblitz.com/edit/vpdt6g?file=package.json

**Comment by marcioluish** [comment]
Hi @cetincakiroglu, thanks for looking into it.
However, `expanded` property is still not working.

**Comment by imaksp** [comment]
Hi @psarno it also broke our app, we are also simply using panel menu only on mobile view with static item array with label command & routerLink & this version has introduced infinite loop in our app, most likely due to PR which was supposed to fix this issue.
related issue:
https://github.com/primefaces/primeng/issues/15057

**Comment by cetincakiroglu** [comment]
Hi,

Re-opened and transferred in v17.12.0 milestone.

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for the feedback, I've found that there is a missing condition in the if statement in line 131 of panelMenuSub component which causes the issue of child expansion on root list item click. Rendering issue is fixed for good. 

Could you please test it after the release?

**Comment by marcioluish** [comment]
> Hi,
> 
> Thanks for the feedback, I've found that there is a missing condition in the if statement in line 131 of panelMenuSub component which causes the issue of child expansion on root list item click. Rendering issue is fixed for good.
> 
> Could you please test it after the release?

Hi @cetincakiroglu thanks for checking this out. Yes, I'll try it as soon fix is released.
Thanks.

**Comment by marcioluish** [comment]
> > Hi,
> > Thanks for the feedback, I've found that there is a missing condition in the if statement in line 131 of panelMenuSub component which causes the issue of child expansion on root list item click. Rendering issue is fixed for good.
> > Could you please test it after the release?
> 
> Hi @cetincakiroglu thanks for checking this out. Yes, I'll try it as soon fix is released. Thanks.

Hi @cetincakiroglu 17.12 still fails to manage `expand` and `label` MenuItem's properties.
Below is a GIF testing it:

![17_12-panelMenu](https://github.com/primefaces/primeng/assets/60225443/001220dc-7a6e-4b71-9f28-8bdf4a647d5c)

And below is the modified stackblitz link of 17.12 PanelMenu's [Multiple](https://primeng.org/panelmenu#multiple). Please have a look at it again to see if anything is wrong when trying to set those MenuItem's properties.
https://stackblitz.com/edit/sg4yxy?file=package.json

Desirable behavior would be the same that we had in 16.0.2 (first GIF of this card)

Thanks again.

**Comment by cetincakiroglu** [comment]
> > > Hi,
> > > Thanks for the feedback, I've found that there is a missing condition in the if statement in line 131 of panelMenuSub component which causes the issue of child expansion on root list item click. Rendering issue is fixed for good.
> > > Could you please test it after the release?
> > 
> > 
> > Hi @cetincakiroglu thanks for checking this out. Yes, I'll try it as soon fix is released. Thanks.
> 
> Hi @cetincakiroglu 17.12 still fails to manage `expand` and `label` MenuItem's properties. Below is a GIF testing it:
> 
> ![17_12-panelMenu](https://private-user-images.githubusercontent.com/60225443/317745309-001220dc-7a6e-4b71-9f28-8bdf4a647d5c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzY3NjMsIm5iZiI6MTcxMTYzNjQ2MywicGF0aCI6Ii82MDIyNTQ0My8zMTc3NDUzMDktMDAxMjIwZGMtN2E2ZS00YjcxLTlmMjgtOGJkZjRhNjQ3ZDVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE0MzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkODJjMDcyNDMzYzYwM2RlNTA0MzdmNmFmOWYyNzUyNjYxMDdmMmYzMjNjODRlOTg1ZjE0YWI2MGRiYTNjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tuwoXCiMf5tN2OtonZWfjBBp11WKGbIQBwJL3QdAbhQ) [ ![17_12-panelMenu](https://private-user-images.githubusercontent.com/60225443/317745309-001220dc-7a6e-4b71-9f28-8bdf4a647d5c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzY3NjMsIm5iZiI6MTcxMTYzNjQ2MywicGF0aCI6Ii82MDIyNTQ0My8zMTc3NDUzMDktMDAxMjIwZGMtN2E2ZS00YjcxLTlmMjgtOGJkZjRhNjQ3ZDVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE0MzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkODJjMDcyNDMzYzYwM2RlNTA0MzdmNmFmOWYyNzUyNjYxMDdmMmYzMjNjODRlOTg1ZjE0YWI2MGRiYTNjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tuwoXCiMf5tN2OtonZWfjBBp11WKGbIQBwJL3QdAbhQ) ](https://private-user-images.githubusercontent.com/60225443/317745309-001220dc-7a6e-4b71-9f28-8bdf4a647d5c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzY3NjMsIm5iZiI6MTcxMTYzNjQ2MywicGF0aCI6Ii82MDIyNTQ0My8zMTc3NDUzMDktMDAxMjIwZGMtN2E2ZS00YjcxLTlmMjgtOGJkZjRhNjQ3ZDVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE0MzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkODJjMDcyNDMzYzYwM2RlNTA0MzdmNmFmOWYyNzUyNjYxMDdmMmYzMjNjODRlOTg1ZjE0YWI2MGRiYTNjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tuwoXCiMf5tN2OtonZWfjBBp11WKGbIQBwJL3QdAbhQ) [ ](https://private-user-images.githubusercontent.com/60225443/317745309-001220dc-7a6e-4b71-9f28-8bdf4a647d5c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzY3NjMsIm5iZiI6MTcxMTYzNjQ2MywicGF0aCI6Ii82MDIyNTQ0My8zMTc3NDUzMDktMDAxMjIwZGMtN2E2ZS00YjcxLTlmMjgtOGJkZjRhNjQ3ZDVjLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE0MzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkODJjMDcyNDMzYzYwM2RlNTA0MzdmNmFmOWYyNzUyNjYxMDdmMmYzMjNjODRlOTg1ZjE0YWI2MGRiYTNjYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tuwoXCiMf5tN2OtonZWfjBBp11WKGbIQBwJL3QdAbhQ)
> 
> And below is the modified stackblitz link of 17.12 PanelMenu's [Multiple](https://primeng.org/panelmenu#multiple). Please have a look at it again to see if anything is wrong when trying to set those MenuItem's properties. https://stackblitz.com/edit/sg4yxy?file=package.json
> 
> Desirable behavior would be the same that we had in 16.0.2 (first GIF of this card)
> 
> Thanks again.

Hi,

I guess the problem is that the change detection is not triggered. I can make it work a little bit refactoring https://stackblitz.com/edit/sg4yxy-rnqdjm?file=package.json,src%2Fapp%2Fdemo%2Fpanel-menu-multiple-demo.ts

**Comment by marcioluish** [comment]
> Hi,
> 
> I guess the problem is that the change detection is not triggered. I can make it work a little bit refactoring https://stackblitz.com/edit/sg4yxy-rnqdjm?file=package.json,src%2Fapp%2Fdemo%2Fpanel-menu-multiple-demo.ts

Also @cetincakiroglu, I noticed that when manipulating `expanded`  property and triggering change detection (by assigning new values to MenuItem's `items` array), we have a little issue between `angledownicon` and `anglerighticon`, where collapsed items still show the `angledownicon`:

![image](https://github.com/primefaces/primeng/assets/60225443/316032f8-8220-453a-b884-512135ed448e)

Is this something that can be prevented without explicitly using html manipulation?

**Comment by cetincakiroglu** [comment]
> > Hi,
> 
> > 
> 
> > I guess the problem is that the change detection is not triggered. I can make it work a little bit refactoring https://stackblitz.com/edit/sg4yxy-rnqdjm?file=package.json,src%2Fapp%2Fdemo%2Fpanel-menu-multiple-demo.ts
> 
> 
> 
> Also @cetincakiroglu, I noticed that when manipulating `expanded`  property and triggering change detection (by assigning new values to MenuItem's `items` array), we have a little issue between `angledownicon` and `anglerighticon`, where collapsed items still show the `angledownicon`:
> 
> 
> 
> ![image](https://github.com/primefaces/primeng/assets/60225443/316032f8-8220-453a-b884-512135ed448e)
> 
> 
> 
> Is this something that can be prevented without explicitly using html manipulation?

Hi, thanks for letting us know. We'll  check the issue again before the 17.14.0 release.

**Comment by josefKiefer** [comment]
> > > Hi,
> > 
> > 
> > > 
> > 
> > 
> > > I guess the problem is that the change detection is not triggered. I can make it work a little bit refactoring https://stackblitz.com/edit/sg4yxy-rnqdjm?file=package.json,src%2Fapp%2Fdemo%2Fpanel-menu-multiple-demo.ts
> > 
> > 
> > Also @cetincakiroglu, I noticed that when manipulating `expanded`  property and triggering change detection (by assigning new values to MenuItem's `items` array), we have a little issue between `angledownicon` and `anglerighticon`, where collapsed items still show the `angledownicon`:
> > ![image](https://private-user-images.githubusercontent.com/60225443/318515488-316032f8-8220-453a-b884-512135ed448e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTM2MTUsIm5iZiI6MTczMDI1MzMxNSwicGF0aCI6Ii82MDIyNTQ0My8zMTg1MTU0ODgtMzE2MDMyZjgtODIyMC00NTNhLWI4ODQtNTEyMTM1ZWQ0NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAxNTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYzQ0MDNmMmNmODg0MzMwMjY3NWQ0MDQ3NGY2MGRiMDhmOTUzZmYzMzU4MDRmYmM5NzExMjE2NjUyNzU2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CSf_3QI6EmukIlgfE5s9AvVZcfh-ZylpNIuTWcqWxHI)
> > Is this something that can be prevented without explicitly using html manipulation?
> 
> Hi, thanks for letting us know. We'll check the issue again before the 17.14.0 release.

Hello,

Is there any update on this? I'm seeing this issue in my app and we're on 17.18.11. The demo on your website seems to be on the same version and has the same issue: https://primeng.org/panelmenu#controlled

To repro at that link:

1. Click Users > New > Member
2. Click another top level menu (such as Calendar)
3. Click Users again and see that the New submenu is using the angledownicon instead of the anglerighticon. In addition, when clicking on the New submenu, there is no animation to open it up.

![image](https://github.com/user-attachments/assets/dc15ad0d-140a-4159-ad42-c3ee8d146dd4)

Thanks in advance!
