### ISSUE TITLE
Date filter on  table  v18

### ISSUE THREAD

**Issue by hm-kynecto** [primefaces/primeng#16354]
### Describe the bug

On selecting the date picker we get

```
Calendar component is deprecated as of v18, use DatePicker component instead.
core.mjs:7211 ERROR TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at _DomEventsPlugin.addEventListener (platform-browser.mjs:846:13)
    at _EventManager.addEventListener (platform-browser.mjs:208:19)
    at NoneEncapsulationDomRenderer.listen (platform-browser.mjs:727:30)
    at AnimationRenderer.listen (browser.mjs:4340:26)
    at _Calendar.bindDocumentResizeListener (primeng-calendar.mjs:4685:51)
    at _Calendar.onOverlayAnimationDone (primeng-calendar.mjs:4170:16)
    at Calendar_div_3_Template_div_animation_overlayAnimation_done_0_listener (primeng-calendar.mjs:1317:36)
    at executeListenerWithErrorHandling (core.mjs:25794:12)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:25826:18)
    at browser.mjs:4422:28
```
    

https://v18.primeng.org/table  says use 

```
 <div class="flex items-center">
                    Date
                    <p-columnFilter type="date" field="date" display="menu" />
                </div>
```
    
    
 how can we use the date filter in v18?

### Environment

development env

 "primeng": "^18.0.0-beta.1",

### Angular version

18

### PrimeNG version

18

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.1

### Expected behavior

date filter should work

**Comment by cetincakiroglu** [comment]
Hi, this issue has been fixed with the v18.0.0-beta.2, could you please check and confirm?

**Comment by hm-kynecto** [comment]
@cetincakiroglu   

the date picker now works correctly however my row contains date and time,   when applying the filter and resetting it the visual data sets the hours to 00.00

I guess its related to this

https://github.com/primefaces/primeng/issues/15684


![image](https://github.com/user-attachments/assets/7168c340-968f-466c-bb50-c5ea1bf30f50)

![image](https://github.com/user-attachments/assets/3064764a-cf3c-4301-8168-d490d66b492f)

![image](https://github.com/user-attachments/assets/4c56c7c0-b3b2-4300-880e-065d29e0c851)

**Comment by ray-kay** [comment]
Hi,

this is bug as described still exists in version 18.0.0 (stabel):
![image](https://github.com/user-attachments/assets/d1b943e9-6bb0-49b8-ac6e-9619a18b3568)


`<ng-template
				pTemplate="header"
				let-columns
			>
				<tr>
					@for (col of columns; track col) {
						<th
							scope="col"
							[pSortableColumn]="col.field"
						>
							{{ col.translation }}
							<p-sortIcon [field]="col.field" />
							<p-columnFilter
								[type]="col.filterType"
								[field]="col.field"
								display="menu"
								hideOnClear="true"
								maxFractionDigits="5"
							/>
						</th>
					}
				</tr>
			</ng-template>`
