### ISSUE TITLE
datatable header doesn't display when scrollable is set to true for ColGroup

### ISSUE THREAD

**Issue by srinigowda** [primefaces/primeng#1637]
![afterscrollabletrue](https://cloud.githubusercontent.com/assets/44777/21349456/16b56eac-c6d8-11e6-80b1-ca9c4910f8a0.png)
![beforescrollabletrue](https://cloud.githubusercontent.com/assets/44777/21349457/16b98aa0-c6d8-11e6-9a96-751234993038.png)

**Comment by ctrl-brk** [comment]
https://github.com/primefaces/primeng/issues/1600#issuecomment-268235330

**Comment by wuzhouyang** [comment]
Hey! Resolve it?

**Comment by benjamincharity** [comment]
It should be fixed in 1.1.4: https://github.com/primefaces/primeng/issues/1600#issuecomment-270766675

**Comment by wuzhouyang** [comment]
I update the primeng to the 1.1.4 but the problem still exists

**Comment by benjamincharity** [comment]
Ahh sorry possibly it is a different issue then..

**Comment by wuzhouyang** [comment]
Do you have any good solutions？

**Comment by benjamincharity** [comment]
Not off the top of my head since I cannot replicate (and thought this was solved 😞). If someone creates an plunker/codepen/etc of this issue I'd be willing to take a look.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

<img width="1086" alt="screen shot 2017-06-19 at 13 35 37" src="https://user-images.githubusercontent.com/686247/27281350-395239b8-54f4-11e7-84cf-a93105aaf855.png">
