### ISSUE TITLE
Select component style issues

### ISSUE THREAD

**Issue by kszmetena** [primefaces/primeng#16485]
### Describe the bug
I just started to use the new primeng v.18 and bumped into the following style issues at select component.
1. In the [invalid style](https://github.com/primefaces/primeng/blob/dccc5d2fa7b40f25c49834c1ef6a57f515f9568e/src/app/components/select/style/selectstyle.ts#L200C24-L200C29) of Select component has a reference to css var of SelectButton component. As I noticed every css var of component created dynamically when a component created, so if you don't have SelectButton component your app, the referenced css var is not created and the invalid style is broken of your Select component.

1. When I use with float label the label is not floating out when an item is selected and the focus is outside of select. The `p-inputwrapper-filled` class is not added to select when it's filled. I chekced and the [bool expression is wrong in style ts file](https://github.com/primefaces/primeng/blob/dccc5d2fa7b40f25c49834c1ef6a57f515f9568e/src/app/components/select/style/selectstyle.ts#L213C13-L213C141).

### Environment

It doesn't matter :)

### Angular version

18.2.6

### PrimeNG version

18.0.0-beta.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

22.3.0

### Steps to reproduce the behavior

1. Add the Select component to your app without using of SelectButton component
2. Use the Select component with float label and select an item and click outside of select.

### Expected behavior

1. The style of invalid select component shouldn't have to rely on SelectButton css var.
2. The proper bool expression: `'p-inputwrapper-filled': instance.modelValue() !== undefined && instance.modelValue() !== null && !!instance.modelValue().length`,

**Comment by cetincakiroglu** [comment]
Hi,

The issue is not valid as of v18.0.0-beta.2. Styles of the select component loads without SelectButton and p-inputwrapper-filled class can also be added. See the example below. Closing the issue.

https://stackblitz.com/edit/stackblitz-starters-hav98t?file=src%2Fmain.ts

**Comment by cetincakiroglu** [comment]
Hi,

Thanks for reporting the issue, this issue has been fixed and the fix will be available with upcoming v18.0.0-beta.3 release this week. 

See the line: https://github.com/primefaces/primeng/commit/bf8423bbc53a02f050846e79bae1dc02cd1ad5a8#diff-2bad67681b4a3738b8209aeb7fd6386d5ddfb902764d56de95d73ab3b1093dd8R200

**Comment by YouZag** [comment]
I'd say this isn't fixed.  p-inputwrapper-filled is the default style before it's filled and then undefined is added after.
