### ISSUE TITLE
v18 p-columnFilter: Column filtering indicator is missing

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#16576]
### Describe the bug

In PrimeNG v18 when a table column is filtered  using the p-columnFilter component there is no indication of filtering in the corresponding table column header.

**Note:  When viewing the screenshots listed below and the videos listed below,  you may want to use "full screen mode",  because the "highlighting" of the background colors of the v17 filter icons buttons can be hard to see.** 

The following screenshot compares the "**correct**" v17 filter table demo after filtering vs "**incorrect**" v18 filter table demo after filtering:

![Angular_Table_Component_and_Angular_Table_Component_and_Angular_Select_Component](https://github.com/user-attachments/assets/bf551750-af72-47dc-963e-e2c1e0c29297)

The following screenshot compares the style of the filtered name button element for v17 and v18

![Angular_Table_Component_and_Angular_Table_Component_and_History_for_src_app_components_megamenu_megamenu_ts_-_primefaces_primeng_and_Angular_Select_Component](https://github.com/user-attachments/assets/f32dac3f-6f10-47c9-bc84-bba67a75d808)

The following video shows the v17 Table Advanced Filter demo "**indicating**" that column filters are set

https://github.com/user-attachments/assets/c40b22d0-337d-4163-9d2e-d06295ed3bbe

The following video shows the v18 Table Advanced Filter demo  "**not indicating**" that column filters are set

https://github.com/user-attachments/assets/b18edccb-1927-4226-ae0a-770eea155033

### Environment

n/a

### Reproducer

https://v18.primeng.org/table#filter-advanced

### Angular version

18.x

### PrimeNG version

18.0.0.beta-3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

n/a

### Browser(s)

chrome, firefox, safari

### Steps to reproduce the behavior

1. Run the v18 Table  Filter Advance Demo: https://v18.primeng.org/table#filter-advanced
2. Filter for one or more columns
--- After the table is filtered there will be no indications in the table that any of the  filters have been set  (bad)

### Expected behavior

When a column filter is set the corresponding column filter has a visual indication that it has been set.

I.e.  v18 column filter set indicating functionality should work similarly to the current v17 functionality

**Comment by cagataycivici** [comment]
It seems to be missing yes but we can't add a new token right now due to RC stage, it'll be fixed in v18.1.0. Also an issue in PrimeVue which should be fixed in v4.3.0.

**Comment by shaman-apprentice** [comment]
> It seems to be missing yes but we can't add a new token right now due to RC stage, it'll be fixed in v18.1.0. Also an issue in PrimeVue which should be fixed in v4.3.0.

From my point of view, there is nothing to be said against adding a new feature (token) with a reasonable default to a RC. Shouldn't break anything, so why not? Of course, it is your call to make 👍

**Comment by aberonni** [comment]
@cagataycivici @mertsincan FYI I still encounter the issue (also on the documentation website) with v18.0.2 and v19.0.2

**Comment by critchie** [comment]
v17 handled it at [line 5148 in table.ts](https://github.com/primefaces/primeng/blob/4af8e687f3d01f09943036c2ceb1c2e71f11b8aa/src/app/components/table/table.ts#L5148) I think.

But v18 and beyond uses a completely different approach that I couldn't quite figure out but it definitely broke the filter active class.

**Comment by ivan-price-acted** [comment]
hi there, we're seeing this too, it's pretty impactful for us because we initiate our tables with active filters, and we were relying on the column header icon indicator to inform the users what filters were being used (in v17)

has anyone developed a workaround while we wait for the class to be added ? otherwise we'll need to write a function/directive that inspects the underlying pTable filters and re-determines if there is a filter on a column i suppose.

**Comment by ivan-price-acted** [comment]
in case it's interesting to anyone encountering this we managed to build a workaround via an [ngClass] on the table column which returns a specific class if the given column has an active filter.. something like:

```
hasActiveFilter (columnKey: string): string {
  if (Object.hasOwn(this.pTable.filters, columnKey)) {
    let filter = this.pTable.filters[columnKey]
    if (!Array.isArray(filter)) {
      filter = [filter]
    }
    if (filter[0].value && filter[0].value !== 0) {
      return 'active-filter'
    }
  }
  return ''
}
```
.. until the issue is fixed in primeNG

**Comment by cagataycivici** [comment]
This is fixed in our new shared theming package, PrimeNG v19.1.0 will migrate to this new package and issue will be resolved. Minor dom change would be necessary as well, fix is verified in PrimeVue 4.3.0. Retargeting to v19.1.0.

Here is the new package that all Prime UI libraries will be using, instead of ports, there is now a single source of truth. PrimeNG styles will not be a ported one anymore resulting in revamped quality as issues from ports will disappear.

https://github.com/primefaces/primeuix/tree/main/packages/themes

**Comment by GaetanRouzies** [comment]
Still reproducible in 19.1.3.
This issue significantly impacts visual feedback—without it, all tables appear broken to users.

**Comment by davide-bontempelli-zupit** [comment]
@cagataycivici This is not fixed yet and in fact it is also present on your website 

<img width="1469" height="575" alt="Image" src="https://github.com/user-attachments/assets/2e63c09e-7197-4bc1-bb10-f430291f7395" />

**Comment by darcoola** [comment]
I see it fixed in v20, will it be also fixed in v19?

**Comment by NormantasN** [comment]
Still find this issue in v20

**Comment by abowen** [comment]
Broken on v19 (Apollo)

It's been around 18 months. Will it get fixed?

**Comment by abowen** [comment]
How to patch it in via patch-package

https://www.npmjs.com/package/patch-package

Based off this commit in v20

https://github.com/primefaces/primeng/commit/e8e712deb3545f3944da45047a000046b2ae1978

In package.json

```
"postinstall": "patch-package",
...
 "patch-package": "^8.0.0",
```

Create a `patches/primeng+19.1.4.patch` (or whatever following convention for your version)

```
--- a/node_modules/primeng/fesm2022/primeng-table.mjs
+++ b/node_modules/primeng/fesm2022/primeng-table.mjs
@@ -7242,7 +7242,8 @@
                 [buttonProps]="filterButtonProps?.filter"
             >
                 <ng-template #icon>
-                    <FilterIcon *ngIf="!filterIconTemplate && !_filterIconTemplate" />
+                    <FilterIcon *ngIf="!filterIconTemplate && !_filterIconTemplate && !hasFilter" />
+                    <svg *ngIf="!filterIconTemplate && !_filterIconTemplate && hasFilter" width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg" [attr.class]="'p-icon'" aria-hidden="true"><path d="M13.7274 0.33847C13.6228 0.130941 13.4095 0 13.1764 0H0.82351C0.590451 0 0.377157 0.130941 0.272568 0.33847C0.167157 0.545999 0.187746 0.795529 0.325275 0.98247L4.73527 6.99588V13.3824C4.73527 13.7233 5.01198 14 5.35292 14H8.64704C8.98798 14 9.26469 13.7233 9.26469 13.3824V6.99588L13.6747 0.98247C13.8122 0.795529 13.8328 0.545999 13.7274 0.33847Z" fill="currentColor"/></svg>
                     <span class="pi-filter-icon" *ngIf="filterIconTemplate || _filterIconTemplate">
                         <ng-template *ngTemplateOutlet="filterIconTemplate || _filterIconTemplate; context: { hasFilter: hasFilter }"></ng-template>
                     </span>
@@ -7395,7 +7396,8 @@
                 [buttonProps]="filterButtonProps?.filter"
             >
                 <ng-template #icon>
-                    <FilterIcon *ngIf="!filterIconTemplate && !_filterIconTemplate" />
+                    <FilterIcon *ngIf="!filterIconTemplate && !_filterIconTemplate && !hasFilter" />
+                    <svg *ngIf="!filterIconTemplate && !_filterIconTemplate && hasFilter" width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg" [attr.class]="'p-icon'" aria-hidden="true"><path d="M13.7274 0.33847C13.6228 0.130941 13.4095 0 13.1764 0H0.82351C0.590451 0 0.377157 0.130941 0.272568 0.33847C0.167157 0.545999 0.187746 0.795529 0.325275 0.98247L4.73527 6.99588V13.3824C4.73527 13.7233 5.01198 14 5.35292 14H8.64704C8.98798 14 9.26469 13.7233 9.26469 13.3824V6.99588L13.6747 0.98247C13.8122 0.795529 13.8328 0.545999 13.7274 0.33847Z" fill="currentColor"/></svg>
                     <span class="pi-filter-icon" *ngIf="filterIconTemplate || _filterIconTemplate">
                         <ng-template *ngTemplateOutlet="filterIconTemplate || _filterIconTemplate; context: { hasFilter: hasFilter }"></ng-template>
                     </span>
```



<img width="214" height="55" alt="Image" src="https://github.com/user-attachments/assets/729052d3-a989-45d9-9665-bb3dfb65f0e8" />

Obviously you'll need to tweak the patch to suit your version
