### ISSUE TITLE
DatePicker: "Cannot read properties of null" error when clicking on next/previous month button (18.0.0-beta.3)

### ISSUE THREAD

**Issue by flortsch** [primefaces/primeng#16590]
### Describe the bug

```
client:489 [vite] connecting...
client:608 [vite] connected.
core.mjs:30062 Angular is running in development mode.
zone.js:1201 [Violation] 'focus' handler took 302ms
zone.js:1201 [Violation] 'focus' handler took 258ms
zone.js:1201 [Violation] 'focus' handler took 253ms
zone.js:1201 [Violation] 'click' handler took 266ms
global-error-handler.ts:10 TypeError: Cannot read properties of null (reading 'focus')
    at _DatePicker.updateFocus (primeng-datepicker.mjs:3828:217)
    at primeng-datepicker.mjs:2527:47
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:7041:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at _ZoneImpl.run (zone.js:111:43)
    at zone.js:2538:40
    at _ZoneDelegate.invokeTask (zone.js:402:33)
    at core.mjs:6710:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:6710:30)
handleError @ global-error-handler.ts:10
next @ core.mjs:33150
ConsumerObserver2.next @ Subscriber.js:90
Subscriber2._next @ Subscriber.js:59
Subscriber2.next @ Subscriber.js:32
(anonymous) @ Subject.js:41
errorContext @ errorContext.js:23
Subject2.next @ Subject.js:31
emit @ core.mjs:6583
(anonymous) @ core.mjs:7075
invoke @ zone.js:369
run @ zone.js:111
runOutsideAngular @ core.mjs:6937
onHandleError @ core.mjs:7075
handleError @ zone.js:373
runGuarded @ zone.js:124
api.microtaskDrainDone @ zone.js:2325
drainMicroTaskQueue @ zone.js:588
invokeTask @ zone.js:487
invokeTask @ zone.js:1138
globalCallback @ zone.js:1169
globalZoneAwareCallback @ zone.js:1202
Show 21 more frames
Show less
zone.js:1201 [Violation] 'click' handler took 289ms
```

### Environment

```
<p-datePicker
        [dateFormat]="dateFormat"
        [ngClass]="{ 'opacity-50': readonly }"
        [showOnFocus]="!readonly"
        [id]="field.name"
        [formControlName]="field.name"
        [showIcon]="!readonly"
        [showButtonBar]="true"
        [readonlyInput]="true"
        [minDate]="minDate"
        [maxDate]="maxDate"
        dataType="string"
      >
</p-datePicker>
```

### Angular version

18.2.3

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.20.4

**Comment by nishtha9102** [comment]
Hi can I be assigned this issue @flortsch

**Comment by mplgn** [comment]
Continuation of #16436, which was closed and thought to be fixed for beta-3.

**Comment by jonbeech86** [comment]
I can confirm I am still getting this on beta-3. 
I see its also happening on the docs too but not sure what version that is running, I assume beta-3: https://v18.primeng.org/datepicker

**Comment by Dayonel** [comment]
Hi, I can confirm this bug is still happening in beta-3 and also in your docs.

**Comment by Dayonel** [comment]
Error is gone if chevron buttons next & prev 

have a css class `p-datepicker-next` instead of `p-datepicker-next-button`  _notice -button_

or 

js checks for `'.p-datepicker-prev-button').focus()` instead of `'.p-datepicker-prev').focus()` _notice -button_

![image](https://github.com/user-attachments/assets/52d4606c-f804-4475-81d5-4c3b6a765703)

Same for -next code.

**Comment by Dayonel** [comment]
This temporary solution fixes the bug:
```

        <p-datepicker formControlName="date" appendTo="body">

          <!-- TODO: Remove this on beta-4 -->
          <ng-template pTemplate="footer">
            <p-button class="p-datepicker-prev hidden">Previous</p-button>
            <p-button class="p-datepicker-next hidden">Next</p-button>
          </ng-template>
          <!-- end TODO -->

        </p-datepicker>
```

**Comment by Dayonel** [comment]
Fixed in PR: 16675

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/pull/16675

**Comment by HexawareSivaprakashS** [comment]
I am still facing the issue with **"primeng": "^19.0.0"**. 

`<p-calendar name="expiration" [(ngModel)]="userDetail.expiration" [showIcon]="true"
                            autoZIndex="true" baseZIndex="10000" #expiration="ngModel"
                            placeholder="mm/dd/yyyy" [monthNavigator]="true" [yearNavigator]="true"
                            yearRange="2022:2040" (onSelect)="validateExpiration($event)"
                            (onInput)="validateExpiration($event)"></p-calendar>`

<img width="1358" height="263" alt="Image" src="https://github.com/user-attachments/assets/bea68a3a-ac6b-408c-8a06-191479ebaa15" />
