### ISSUE TITLE
p-multiselect label is not updated when ngModel changes

### ISSUE THREAD

**Issue by mitalikhundiwala** [primefaces/primeng#1696]
If ngModel for the component is updated after initialization, writeValue function is called after ngOnInit and in that case the label doesn't update automatically. Any interaction with component then updates the label.

**Comment by mohan1304** [comment]
I am also facing problem described above and #1697 says its fixed and I can see updateLabel() method in my environments mutiselect.ts. Please let me know how can I fix this issue.

**Comment by mohan1304** [comment]
Is this fix available in PrimeNG 2.0-RC1? If so is this fix related to selected item's label? because I still see label & value of selected item as undefined

**Comment by mpatel-greenyourbills** [comment]
Hi @mohan1304 , Yes this issue is fixed and I can see this fix in 2.0.0-rc.2.

**Comment by mitalikhundiwala** [comment]
Hi @mohan1304 , Yes this issue is fixed. I can see this fix in 2.0.0-rc.2.

**Comment by mohan1304** [comment]
Thanks Mitali for your response. 

I already upgraded to 2.0.0 and I still see the values as undefined. Below is my code in html
<p-multiSelect [options]="services" [(ngModel)]="selectedServices" defaultLabel="Services" styleClass="multi-select" (onChange)="getSelectedServices()">
</p-multiSelect>

and if I am printing the values to console as console.log(selectedServices[i].label),  console.log(selectedServices[i].value). I see both values as undefined.

**Comment by marcosybarraa** [comment]
Same problem
