### ISSUE TITLE
Component: Table sortIconTemplate

### ISSUE THREAD

**Issue by viperage** [primefaces/primeng#17062]
### Describe the bug

When using the sortIconTemplate, both the default and custom sort icons are shown. as dt._sortIconTemplate in p-sortIcon is undefined. when rendered.
```
<ng-template #sortIcon />
```

### Environment

nx

### Angular version

18.2.0

### PrimeNG version

18.0.0

### Build / Runtime

Angular CLI App

### Language

ES6

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

chrome

### Expected behavior

To show only the custom sortIcon

**Comment by mehmetcetin01140** [comment]
Fixed in f9d340043f5432de64a794718d2adf10dea6a98d

**Comment by viperage** [comment]
I managed to get the stackblitz to work, you can  see both the default and provided template appearing

https://stackblitz.com/edit/github-wtg63fux
![image](https://github.com/user-attachments/assets/bc039758-b385-43a4-bd76-a8de511621db)

**Comment by viperage** [comment]
@mehmetcetin01140 was the fix implemented in 18.0.2 as in the stackblitz, its still showing both icons. Thanks

**Comment by ng-multivers** [comment]
> [@mehmetcetin01140](https://github.com/mehmetcetin01140) was the fix implemented in 18.0.2 as in the stackblitz, its still showing both icons. Thanks

When using version 19.0.2 , i have similar issue where both still appear ( default icon invoke by p-sortIcon and ng-template provided #sortIcon )

**Comment by yxlim-dickson** [comment]
@ng-multivers you can also use this method to workaround. By providing both the ptemplate and the templateref the default sorticons wont be created.
```
<ng-template #sorticon pTemplate="sorticon">
...
</ng-template>
```
