### ISSUE TITLE
autocomple multiple : can't display labels

### ISSUE THREAD

**Issue by stephane-tessier** [primefaces/primeng#17332]
### Describe the bug

When using **autocomplete** with **multiple** = true and objects like **[{label: 'toto', value: {}}]**,
**the selected items cannot display their labels properly** : 

```html
<li
                    #token
                    *ngFor="let option of modelValue(); let i = index"
                    [ngClass]="{ 'p-autocomplete-chip-item': true, 'p-focus': focusedMultipleOptionIndex() === i }"
                    [attr.id]="id + '_multiple_option_' + i"
                    role="option"
                    [attr.aria-label]="getOptionLabel(option)"
                    [attr.aria-setsize]="modelValue().length"
                    [attr.aria-posinset]="i + 1"
                    [attr.aria-selected]="true"
                >
```
**let option of modelValue()** is wrong : it's not an option (label+value) but only a value.
This should be renamed as **value**, and a function similar to **inputValue()** should be used to fetch the selected options among the options list

BR

### Reason for not contributing a PR

- [X] Lack of time
- [X] Unsure how to implement the fix/feature
- [X] Difficulty understanding the codebase
- [ ] Other

### Reproducer

x

### Environment

prime 18.0.2

### Angular version

18.0.2

### PrimeNG version

v18 (LTS Only)

### Steps to reproduce the behavior

use an autocomplete with complexe objects

### Expected behavior

labels should display properly

**Comment by davidda** [comment]
Can you provide a stackblitz reproducer? I think have this scenario in my application and it works fine. You have to set the [optionLabel] property of the p-autocomplete.

**Comment by stephane-tessier** [comment]
https://stackblitz.com/edit/stackblitz-starters-uppvnx3z?file=src%2Fapp%2Fapp.component.ts

**Comment by BeGj** [comment]
Bump

**Comment by WillBoig** [comment]
We have the same issue on our apps and this makes it impossible to finalize the upgrade to primeng19. I confirm that the stackblitz linked by @stephane-tessier reproduces the exact issue we have.

**Comment by WillBoig** [comment]
The issue is still present in primeng 19.0.10. I have updated the stackblitz of @stephane-tessier to show that it does not work with multiple attribute or without it : 

[https://stackblitz.com/edit/stackblitz-starters-gdwelehl?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/stackblitz-starters-gdwelehl?file=src%2Fapp%2Fapp.component.html)

**Comment by ryann3588** [comment]
A work around I found to work is to map the select item to itself i.e.

{ label: '', value: '', item: { label: '', value: '' }}

Then set optionValue="item"

**Comment by gmaggiodev** [comment]
Yesterday, created a pull request that fix the issue.

Please review asap: https://github.com/primefaces/primeng/pull/18044 

![Image](https://github.com/user-attachments/assets/fe070673-25ec-4d7a-aa8f-a0f7333127ad)

![Image](https://github.com/user-attachments/assets/62a60a00-5baa-42d8-9ef5-e81286241230)

**Comment by rlittolff-rofim** [comment]
6 months without a fix ?!
There is a PR but nobody merge it.

Please fix this quickly.

In the meantime, we're using [ryann3588](https://github.com/ryann3588)'s work around

**Comment by mertsincan** [comment]
Fixed for next version. 

@gmaggiodev could you please check the fix? Thanks a lot!

**Comment by gmaggio-ca** [comment]
> Fixed for next version.
> 
> [@gmaggiodev](https://github.com/gmaggiodev) could you please check the fix? Thanks a lot!

@mertsincan I've just tested it using the showcase extension with problem use case that I wrote in my PR (https://github.com/primefaces/primeng/pull/18044) but it works partially. I still have a problem when passing initially the selection array (as array of codes). It doesn't resolve its labels:

<img width="1083" height="427" alt="Image" src="https://github.com/user-attachments/assets/f9f1f447-5694-404b-8dc4-151fb0d2fff6" />

I can do a PR with new showcase docs to make easier for you reproducing the cases (or you can pick it from my PR).

Let me know
