### ISSUE TITLE
p-dialog: close button not visible  [19.0.4]

### ISSUE THREAD

**Issue by imaksp** [primefaces/primeng#17335]
### Describe the bug

dialog doesn't display close button in 19.0.4.
<img width="553" alt="dialog-close" src="https://github.com/user-attachments/assets/d9be12fa-6430-4d1f-9989-ca7e68e30044" />

### Reason for not contributing a PR

- [ ] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [X] Other

### Other Reason

Regression, 

### Reproducer

https://stackblitz.com/edit/stackblitz-starters-bodgow7v?file=package.json,src%2Fapp%2Fapp.component.html

### Environment

NA

### Angular version

19.x

### PrimeNG version

v19

### Steps to reproduce the behavior

go to: https://stackblitz.com/edit/stackblitz-starters-bodgow7v?file=package.json,src%2Fapp%2Fapp.component.html
& click Show button.

### Expected behavior

It should show close button like before.

**Comment by sandrotonon** [comment]
Same problem at ConfirmDialog. See https://stackblitz.com/edit/stackblitz-starters-pxyhwgp9?file=src%2Fapp%2Fapp.component.html

**Comment by rosenthalj** [comment]
The PrimeNG 19 dialog demos fail to display the close button. Note:  The button exists and you can click on it.  Also you can "barely" see the background color when hovering the mouse over the button.

This video shows v19.0.4 dialog demo missing the close button


https://github.com/user-attachments/assets/56562eb9-4d2e-4e84-aac0-2bcba04ec06d

**Comment by mateustormin** [comment]
Just updated my app to v19.0.4 and not only the dialog close button, but I also have a set o buttons to change app theme and they show the image but doesn't show the label:

```
<p-button [label]="itm.label" [text]="true" size="small" iconPos="top" (onClick)="changeTheme(itm.preset)" *ngFor="let itm of availableThemes">
    <img [src]="itm.src" width="30">
</p-button>
```

**Comment by imaksp** [comment]
Closing as fixed in `19.0.5`,  see issue #17338.

**Comment by VicTMPDeV** [comment]
Just updated my project to 19.0.5 and close buttons still not appearing on Dynamic Dialog component.

**Comment by Yewo-Devs** [comment]
It appears the issue has resurfaced in v20.0.0
