### ISSUE TITLE
ConfirmDialog defaultFocus set to accept does not work

### ISSUE THREAD

**Issue by hmn** [primefaces/primeng#17566]
### Describe the bug

When using the defaultFocus option on ConfirmDialog does not workm the focus is not set and the default value when using space/enter is always reject

The default should also be "accept" and if I try the basic example on https://primeng.org/confirmdialog it also has the error

I tried setting defaultFocus both on the <p-confirmdialog> html tag and the confirm service and both methods has the error

![Image](https://github.com/user-attachments/assets/332af045-083b-4725-9917-ce70329613e3)

First time I click on a button the reject function has focus, but if I then click on the other button then focus is never showed again, and accept never has focus

### Reason for not contributing a PR

- [ ] Lack of time
- [x] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/6mpyctya?file=src%2Fapp%2Fconfirm-dialog-basic-demo.html

### Environment

recreated error on default example

### Angular version

19.0.1

### PrimeNG version

v19

### Steps to reproduce the behavior

1. Open https://primeng.org/confirmdialog
2. Click "Save" button in first example
3. Press enter and verify cancel action is run

### Expected behavior

1. Focus is on "Cancel" button but it should have been on "Save" button
2. Reject function is run but default should have been accept

**Comment by mehmetcetin01140** [comment]
fixed in [f248236](https://github.com/primefaces/primeng/pull/18074/commits/f248236cad7be2533d7219ecec8b2e1a520cbfe1)

**Comment by Celebes** [comment]
> fixed in [f248236](https://github.com/primefaces/primeng/pull/18074/commits/f248236cad7be2533d7219ecec8b2e1a520cbfe1)

This still doesn't work in version 19.1.4, if I understand correctly the merge request was closed without merging your fix
