### ISSUE TITLE
ConfirmDialog breakpoints does not work

### ISSUE THREAD

**Issue by alezhu** [primefaces/primeng#17753]
### Describe the bug

The ConfirmDialog component receives the breakpoints input property and generates corresponding CSS @media classes for it. However, it assigns names in the format .p-dialog[pn_id_<id>], where <id> is the identifier of the ConfirmDialog component itself, not the ID of the internal p-dialog component. As a result, the CSS classes do not work as intended. Meanwhile, the p-dialog component is capable of accepting the breakpoints property directly and correctly generates the appropriate class names.

### Pull Request Link

https://github.com/primefaces/primeng/pull/17741

### Reason for not contributing a PR

- [ ] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/github-l4xbyctn?file=src%2Fapp%2Fapp.component.html

### Environment

Windows

### Angular version

19.1.7

### PrimeNG version

v19

### Node version

22.11.0

### Steps to reproduce the behavior

1. Open https://stackblitz.com/edit/github-l4xbyctn?file=src%2Fapp%2Fapp.component.html
2. Click Confirm button
3. Resize preview window
4. On 768px width and less confirm dialog must be 100% width, but it does not

### Expected behavior

In stackblitz example on 768px width and less confirm dialog must be 100% width

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/pull/17713

**Comment by alezhu** [comment]
@cetincakiroglu No. It is not fixed. You did not merge my PR, and did not fix it youself.
