### ISSUE TITLE
Most of the PrimeNG examples do not work fully in StackBlitz (when clicking Edit in StackBlitz)

### ISSUE THREAD

**Issue by naris** [primefaces/primeng#17830]
### Describe the bug

Most of the PrimeNG examples, such as the table filtering examples, do not work fully in StackBlitz (when clicking Edit in StackBlitz). While the examples do work in the documentation itself, if you click the lightning bolt "Edit in StackBLitz" button they do not. Some can be manually edited to fix incorrect paths (such as '@/service/customerservice' to '../service/customerservice') so the example at least runs, but with missing images 
 and bad formatting, etc.

While most can usually be edited to make workable after stumbling around in the code, this is a bad look and not helpful.

### Reason for not contributing a PR

- [ ] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [x] Other

### Other Reason

The bug is in the examples in the documentation, not in primeng itself.

### Reproducer

https://primeng.org/table#filter-advanced

### Environment

Wiundows 11, StackBlitz

### Angular version

19.0.1?

### PrimeNG version

v19

### Browser(s)

Edge

### Steps to reproduce the behavior

1. Go to the Table Advanced Filter example
2. Click the Lightning bolt Edit in StackBlitz button
3. The StackBlitz example will eventually fail to compile and will not start

I have seen this happen with most of the other examples for other components as well.

### Expected behavior

The examples in the documentation should work when clicking the Lightning Bolt "Edit in StackBlitz" button.

**Comment by DanielOberlechner** [comment]
Wanted to create today also an issue about the same topic.
There are really a lot of examples which don't work currently.

Sometimes the import is wrong, or on the radio button site there is <p-radiobutton> used but only <p-radioButton> or <p-radio-button> does work with the newest version.

The maintainers should really check their documentation and fix the bugs in it.

Daniel

**Comment by jsebastian2707** [comment]
![Image](https://github.com/user-attachments/assets/d578151a-43ee-45a4-8b97-17ee96672c80) 

same problem, the imports are not working in the examples 😔

**Comment by mehmetcetin01140** [comment]
fixed in https://github.com/primefaces/primeng/commit/ef43042c35f9e88229ee2636b2ff95b375d6194e

**Comment by DanielOberlechner** [comment]
https://primeng.org/radiobutton
Radio Button disabled has a still not working stackblitz example ....

**Comment by adama357** [comment]
The Table filter example still isn't working, so I created a new issue about it here: #18328 (since this issue was closed).

**Comment by YorleyEspitia** [comment]
same problem


import { AppConfigService } from '@/service/appconfigservice'; //error


✘ [ERROR] TS2304: Cannot find name 'DesignerService'. [plugin angular-compiler]

    src/app/chart-line-style-demo.ts:20:29:
      20 │     designerService = inject(DesignerService);
         ╵                              ~~~~~~~~~~~~~~~


✘ [ERROR] TS2339: Property 'transitionComplete' does not exist on type 'unknown'. [plugin angular-compiler]

    src/app/chart-line-style-demo.ts:25:31:
      25 │         if (this.configService.transitionComplete()) {
         ╵                                ~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS2339: Property 'preset' does not exist on type 'unknown'. [plugin angular-compiler]

    src/app/chart-line-style-demo.ts:26:37:
      26 │             if (this.designerService.preset()) {
