### ISSUE TITLE
Bug: FileUpload | Newly added files not displayed until item is removed (since v20, both modes affected)

### ISSUE THREAD

**Issue by StefaniOSApps** [primefaces/primeng#18559]
### Describe the bug

Since upgrading to PrimeNG v20, the `FileUpload` component does not show newly added files in the file list immediately after selection. This issue occurs in both "basic" and "advanced" mode. The selected files are only rendered in the list after one of the already listed files is removed. This means users do not get any feedback about their selection unless they remove a file, which triggers a re-render.

### Reason for not contributing a PR

- [ ] Lack of time
- [x] Unsure how to implement the fix/feature
- [x] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/run?file=src%2Fapp%2Ffile-upload-advanced-demo.html

### Environment

angular v20
primeng 20.0.0-rc.1

### Angular version

20.0.0-rc.1

### PrimeNG version

v20

### Node version

22.17.0

### Browser(s)

latest chrome

### Steps to reproduce the behavior

1. Update to PrimeNG v20.
2. Use `<p-fileUpload>` in either basic or advanced mode.
3. Select files for upload.
4. Notice that the file list does **not** update to show the newly selected files.
5. Remove a file from the (still-empty) list.
6. Only after removal, the selected files appear in the list.

### Expected behavior

Newly selected files should immediately appear in the file list after selection, without any further interaction required.

**Comment by cagataycivici** [comment]
Fixed in 20.0.0-rc.2 which is available NPM ✅

**Comment by StefaniOSApps** [comment]
@cagataycivici, sorry, but the bug still exists in `20.0.0-rc.2`.

**To reproduce:**

1. Use `<p-fileUpload mode="advanced">`
2. Try to add more than two files.
3. The second file does not appear in the list; only the first is shown.

**Comment by StefaniOSApps** [comment]
pls reopen this issue

**Comment by mertsincan** [comment]
We'll check again. Thanks a lot for your update!

**Comment by mertsincan** [comment]
Hi @StefaniOSApps, I couldn't replicate it. Could you please try it on https://primeng.org/fileupload#advanced?

**Comment by mastersys-giovanni** [comment]
the same for me, both basic and advanced, from the insertion of the second one, it no longer shows

**Comment by mertsincan** [comment]
@mastersys-giovanni , Could you please try it on https://primeng.org/fileupload#advanced? And please check the primeng version in lock file or under node_modules?

**Comment by mastersys-giovanni** [comment]
https://github.com/user-attachments/assets/3748a85b-dec9-412a-89be-5ad7fa056cb7

video from the link above

**Comment by mertsincan** [comment]
@mastersys-giovanni thanks a lot for the video! Fixed now.

**Comment by janfess** [comment]
the bug still exists in advanced mode, I use primeng 20.0.1 and angular 20.1.0, worked fine in version 19 please reopen.

**Comment by feitzi** [comment]
Same here, @mertsincan please reopen this bug!

**Comment by fperie** [comment]
I’m also experiencing a similar issue; when I select a file, it doesn’t appear despite the display template. In V19, this page worked perfectly.

I’m using Angular ^20 (angular-core 20.1.6) and PrimeNG 20.0.1.
Could you please reopen the bug?

**Comment by luchooo87** [comment]
I’m also experiencing a similar issue; when I select a file, it doesn’t appear despite the display template. In V19, this page worked perfectly.

In my case it works fine for images, but it doesn't work for a digital certificate with the .p12 extension.

I’m using Angular ^20 (angular-core 20.1.4) and PrimeNG 20.0.1.
Could you please reopen the bug?

**Comment by Anubis201** [comment]
@janfess @feitzi @fperie @luchooo87  For those who are still experiencing issues with files not showing up after migrating to PrimeNG v20 – the problem comes from a change in how templates are handled. In my case, I had to move the template from pTemplate="file" to pTemplate="content" for the files to display properly. I’m not sure why this was changed, as I couldn’t find any mention of it in the documentation or changelog.
