### ISSUE TITLE
focusOnShow does not work in p-dialog

### ISSUE THREAD

**Issue by wesleydeb** [primefaces/primeng#18816]
### Describe the bug

The focusOnShow property of the PrimeNG dialog component does not work as expected. (see docs: "When enabled, first focusable element receives focus on show.") This property is enabled by default but doesn't do anything.
I've tested this on on the documentation examples (https://primeng.org/dialog) and in their corresponding stackblitz examples by just clicking the show button and checking if the first input in the dialog gets focus automatically. It seems this still worked in v17 but is broken since v18. It still doesn't work in v20.

### Reason for not contributing a PR

- [x] Lack of time
- [ ] Unsure how to implement the fix/feature
- [ ] Difficulty understanding the codebase
- [ ] Other

### Reproducer

https://stackblitz.com/edit/cksxfrrg

### Environment

Windows 11
Edge 139.0.3405.119, Chrome 138.0.7204.183

### Angular version

20.0.4

### PrimeNG version

v20

### Browser(s)

Edge 139.0.3405.119, Chrome 138.0.7204.183

### Steps to reproduce the behavior

1. Go to https://primeng.org/dialog
2. Click the show button in the basic example

### Expected behavior

The first input field in the dialog (the username field) gets focus on show, because the focusOnShow property is by default enabled.
This is what happens when you try this on https://v17.primeng.org/dialog, but doesn't work anymore since https://v18.primeng.org/dialog

**Comment by RadoslawTaborski** [comment]
I noticed something similar with DialogService (for sure in primeng 20.0.1 and 20.1.0). The focus automatically sets to the first control that isn't a regular `<input />` or `<textarea>`. Here's an example: 

https://stackblitz.com/edit/pv1juipc-wgrdck4g

The focus is set to the third control, but the first non-`<input/>` or non-`<textarea>` (In this example, it's `<p-inputNumber/>` but the same behaviour is for dropdown, datepicker and other).

**Comment by meursj** [comment]
Probably related to #18774

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng/pull/18839

**Comment by fmikee** [comment]
This is still not fixed: **all the elements on your demo page on Primeng.org are still autofocus="true".**

The problem is, that on AutoFocus the field @Input('pAutoFocus') autofocus: boolean = false; still has the value "null" in runtime. Probably due to the nature of binding, for example on Button: [pAutoFocus]="autofocus || buttonProps?.autofocus", where both inputs can be null/undefined.

Because of this AutoFocus.onAfterContentChecked sets the autofocus attribute, because this.autofocus IS NOT strictly false: 

 onAfterContentChecked() {
        // This sets the "attr.autofocus" which is different than the Input "autofocus" attribute.
        **_if (this.autofocus === false) { // <- this.autofocus is NULL, not false_**
            this.host.nativeElement.removeAttribute("autofocus");
        } else {
            this.host.nativeElement.setAttribute("autofocus", true);
        }
        if (!this.focused) {
            this.autoFocus();
        }
    }
