### ISSUE TITLE
Calendar selected date is off a day

### ISSUE THREAD

**Issue by d1820** [primefaces/primeng#2426]
#

**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please fork the plunkr below and create a case demonstrating your bug report. Issues without a plunkr have much less possibility to be reviewed.

https://www.primefaces.org/primeng/#/calendar

**Current behavior**
When selecting a date all selctions are off by 1 day less. This is happening on the source site as well.
https://www.primefaces.org/primeng/#/calendar

**Expected behavior**
correct date gets selected

**Minimal reproduction of the problem with instructions**
Visit
https://www.primefaces.org/primeng/#/calendar
use any of the examples and the date is incorrect

**Please tell us about your environment:**
 Macbook Pro

* **Angular version:** 2.0.X
Angular 4.0.0

* **PrimeNG version:** 2.0.X
 "primeng": "4.0.0-rc.2",

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by romejoe** [comment]
I just ran into this issue also. In my case, it looks like the right date is being selected, but the time is midnight GMT. In local time(EST), it's the previous day. Just ended up doing the following temporarily:
`
setDate(value:any) {
    let datey = moment(value);
    this.amendment.date = datey.toISOString();
  }
`


`
<p-calendar *ngIf="!viewonly" class="ui-g-6" dateFormat="yy-mm-dd'T00:00:00.000Z'" [(ngModel)]="target.date"
                  [monthNavigator]="true" [yearNavigator]="true" yearRange="2000:2050" (onSelect)="setDate($event)"></p-calendar>
`

**Comment by dhndeveloper** [comment]
Same issue here

**Comment by clabough** [comment]
Yes, it's converting from UTC time in this part of the code

`selectDate(dateMeta) {
        this.value = new Date(Date.UTC(dateMeta.year, dateMeta.month, dateMeta.day));`

**Comment by dephiros** [comment]
thanks @clabough for the workaround. I change new Date() to d so i don't have to create a time date and also takes account of DST
`
setBirthdate(d: Date) {
	d.setTime(d.getTime() + (d.getTimezoneOffset() * 60 * 1000));
	this.person.birthdate = d;
}
`

**Comment by clabough** [comment]
Just remember that when the original issue is fixed, the workaround will need to be removed.

**Comment by panarenga** [comment]
Thanks for the solution but it did not solve my problem.
If I select 20 April at 10:39 , the function get 19 April 10:39. Then it adds the TimeZoneOffset and it returns 19 April 13:39. 
I think I will have to simply add a day to the date.

**Comment by giovannicandido** [comment]
Confirmed with version 4.0.0-rc.2

**Comment by giovannicandido** [comment]
The problem with the workround is that selecting a time also changes the date :-)

**Comment by Mattpx** [comment]
Thanks @clabough, for some reason the fix was not working all the time for me. Here is what I did to temporarily solve the issue:

`onSelectAdjustDate(date: Date) {

    let dateString = date.toJSON(),
        currentDateString = new Date().toJSON(),
        adjustedDate = new Date(dateString.substr(0, dateString.indexOf('T')) + currentDateString.substr(currentDateString.lastIndexOf('T')));

    this.searchForm.controls['dateStart'].setValue(adjustedDate);
}`

**Comment by Mattpx** [comment]
Thanks @clabough, the fix didn't work constantly on my end. Here is what I did to temporarily solve this:

`onSelect(date: Date) {

    let dateString = date.toJSON(),
        currentDateString = new Date().toJSON(),
        adjustedDate = new Date(dateString.substr(0, dateString.indexOf('T')) + currentDateString.substr(currentDateString.lastIndexOf('T')));

    this.searchForm.controls['startDate'].setValue(adjustedDate);
}`

**Comment by luchillo17** [comment]
I was about to make an issue about this, then updated to latest just because the issue says to check with latest (rc.3 which happened to go out 3 days ago) and since it was fixed i went searching the commit, and from the commit to this issue.

Nice work @cagataycivici, primeng is seriously helping my dev process. 😄

**Comment by ColinMorris83** [comment]
This issue is still occurring if you just type in a date rather than use the datepicker.
e.g. with a calendar with dateFormat="dd-mm-yy" dataType="date" utc="true", if you type in 20-09-1972, the value submitted will end up being 19-09-1972. When injecting the Calendar instance as a ViewChild and logging to the console what its value is, when selected using the datepicker, it has a time of 01:00 with an offset of 1 (GMT), when manually typed and input field blurred, the time value is 00:00 with an offset of 1 (GMT). So something is not quite being set correctly if not using the datepicker.

**Comment by ericrovtar** [comment]
I'm also still having this issue in 4.1.0-rc.3. Any updates on getting this to work without having to modify the value manually?

**Comment by zhangkang1521** [comment]
[dataType]="'string'"

**Comment by fcostazini** [comment]
I'm using version 4.1.3 with formControls and when i set the date by formcontrol.setValue, the date is 1 day off. any sugestion?

**Comment by applitopia** [comment]
4.2.1 Still broken.

**Comment by nieldw** [comment]
It looks like the [commit](https://github.com/primefaces/primeng/issues/2426#event-1042746642) with which @cagataycivici closed this issue later regressed [here in the code](https://github.com/primefaces/primeng/blob/3a635b2225d6c35fa6d90e1c539f600cea107462/src/app/components/calendar/calendar.ts#L691).

Based on that, **workaround** by setting the calendar property `utc="true"`

**Comment by IvayloGoranov** [comment]
I fixed the issue by extending the Calendar class, then hid/rewrote the base class updateModel function, copy/paste its base functionality and added this line 

this.fixUTCDate(this.value); 

in the beginning of the function .
Here is the code of fixUTCDate:

private fixUTCDate(date): void {
        if (date) {
            date.setTime(new Date(new Date(date.getTime() - (date.getTimezoneOffset() * 60 * 
                                                  1000)).toUTCString()));
        }
    }

Works with both selecting the date and typing it manually.

**Comment by nicolecortes** [comment]
> I fixed the issue by extending the Calendar class, then hid/rewrote the base class updateModel function, copy/paste its base functionality and added this line
> 
> this.fixUTCDate(this.value);
> 
> in the beginning of the function .
> Here is the code of fixUTCDate:
> 
> private fixUTCDate(date): void {
> if (date) {
> date.setTime(new Date(new Date(date.getTime() - (date.getTimezoneOffset() * 60 *
> 1000)).toUTCString()));
> }
> }
> 
> Works with both selecting the date and typing it manually.

Thank It works form me

**Comment by TechJignaysa** [comment]
Hi All,

  I am using following version, facing this issue
        "primeng": "^11.2.3",

Resolved using following Code

**Statiic Method to format the date :**
static formatDate(date) {
        let month = date.getMonth() + 1;
        let day = date.getDate();

        if (month < 10) {
            month = '0' + month;
        }

        if (day < 10) {
            day = '0' + day;
        }

        return date.getFullYear() + '-' + month + '-' + day;
    }


**in the .ts file calling static method and setting time to 00:00:00 which solved my issue**
 formatFinalDate(value)
      {
        var dt =  formatDate(value) + 'T00:00:00';
        return  this.objInvoiceHeaderInfo.dueDate = dt;
      }

Let me know if we have any work arround

Thanks,

**Comment by filiptrivan** [comment]
For those using .NET Web API and Angular, this generally solved my issue:

Angular interceptor:
```
import { Injectable } from '@angular/core';
import { HttpInterceptor, HttpRequest, HttpHandler, HttpEvent, HttpResponse } from '@angular/common/http';
import { Observable, tap } from 'rxjs';

@Injectable()
export class JsonHttpInterceptor implements HttpInterceptor {
  private dateRegex = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/;

  constructor() { }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(request)
      .pipe(
        tap((event: HttpEvent<any>) => {
          if (event instanceof HttpResponse) {
            this.convertDates(event.body);
          }
        }
    ));
  }

  private convertDates(
    object: unknown,
    parent?: Record<string, unknown> | unknown[],
    key?: number | string,
  ) {
    if (object === null) return;

    if (typeof object === 'string') {
      if (this.dateRegex.test(object)) {
        /**
         * @see https://stackoverflow.com/a/54733846/1306679
         */

        parent[key] = new Date(object);
      }
    } else if (Array.isArray(object)) {
      for (let i = 0; i < object.length; i++)
        this.convertDates(object[i], object, i);
    } else {
      for (const key of Object.keys(object as Record<string, unknown>)) {
        this.convertDates(
          (object as Record<string, unknown>)[key],
          object as Record<string, unknown>,
          key,
        );
      }
    }
  }

}
```

.NET Web API: (https://stackoverflow.com/questions/69336433/date-issues-using-angular-calling-net-core-web-api-and-sql-server-database)
```
services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.Converters.Add(new JsonDateTimeConverter());
});
```

```
public class JsonDateTimeConverter : JsonConverter<DateTime>
{
    public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return DateTime.Parse(reader.GetString());
    }

    public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToUniversalTime().ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ssZ"));
    }
}
```
