### ISSUE TITLE
p-checkbox template/model driven behaviour disparity

### ISSUE THREAD

**Issue by DavidMorgan92** [primefaces/primeng#2906]
**I'm submitting a ...**
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I originally submitted this as a support request here (https://forum.primefaces.org/viewtopic.php?f=35&t=51096) and was referred here. I assume the behaviour here is unintended so I'm submitting it as a bug.

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/YU4FA98JiXUwfSmnr30N?p=preview

**Current behavior**
Checkbox groups do not produce an array of selected values using the model driven forms method like they do with the template driven forms. An array of only the last checked value is produced.

**Expected behavior**
Checkbox groups work the same with model driven forms as with template driven forms.

* **Angular version:** 2.0.X
4.0.0

* **PrimeNG version:** 2.0.X
4.0.1

**Comment by logan2013** [comment]
any update? thank you

**Comment by fibinger** [comment]
Seems like the milestone 4.1.1 has been dropped for this issue. However I think it's crucial to solve it soon, many people are expecting it.
Would it possible to assign next milestone (4.1.2) to this issue and fix it with higher priority this time?
Thank you :)

**Comment by yoyoyoshi** [comment]
Will this be fixed soon?

**Comment by alismart** [comment]
A workaround would be to bind the selectedValues array via [(ngModel)] to the p-checkbox control in reactive forms.

**Comment by fibinger** [comment]
@alismart Could you provide any little snippet to show how you do it in a nice way?
Probably that's a way to go, since we don't know when this bug is going to be fixed.

**Comment by spetex** [comment]
Just follow the official documentation:
https://www.primefaces.org/primeng/#/checkbox

The primary way of doing it works. The problem is when you want to use reactive forms instead.

**Comment by alismart** [comment]
Most often you won't send the values of reactive form controls directly via http service.
The workaround I came up with:
`<p-checkbox formControlName="category" [(ngModel)]="selectedValues" name="category" value="CE"  label="CE"> </p-checkbox>`

Now in the hand-made object which will carry the final values via http service, would seem like this:
`   const sendData = {
      exist: formModel.exist,
      category: this.selectedValues.toString(),
      country: formModel.country
}`
It's not a solution but it comes to rescue :)

**Comment by ajambrovic** [comment]
Since I need to upgrade and since we're using reactive forms, I couldn't wait for the official fix so I've looked into the issue and found a solution. 

I've forked the submitted plunk and added a fix- basically an override of the Checkbox component: http://plnkr.co/edit/2AKqkAJMCyNRV65ipUXt?p=preview so feel free to use it until the fix is patched in.

It seems that one line of code made all the difference :(

**Comment by fibinger** [comment]
@ajambrovic The idea is really good, is like it. But you should also extend the removeValue() method. Otherwise following result is possible (select all and then deselect all):
![image](https://user-images.githubusercontent.com/1809787/29791188-61734e62-8c3c-11e7-9ddc-a98c20511181.png)

**Comment by ajambrovic** [comment]
@fibinger - Thanks for the info, you are correct; here's the updated Plunker: http://plnkr.co/edit/oLkWTs?p=preview

**Comment by yukiofera** [comment]
@ajambrovic Your solution is very nice. I have tested it however didn't work for me.
Take a look please:
https://github.com/primefaces/primeng/issues/3558
http://plnkr.co/edit/CdAa7OhnQSrkiUbEjEcP?p=preview

Test with you solution:
http://plnkr.co/edit/B2UEP2cDsXcuorxCy46F?p=preview

I think preselection doesn't working for model array.

**Comment by ajambrovic** [comment]
@yukiofera - the solution is basically the old working code, with the find method updated to ES6.

Preselection works in this case, but the error in your plunk is that you are not initializing data correctly, check the updated plnkr: http://plnkr.co/edit/wxPvRpDmYzZSRSs7TVy0?p=preview; when comparing objects in JavaScript, they are the same only if they have the same reference.

**Comment by yukiofera** [comment]
@ajambrovic - Thanks for your reply. 

You are right. I understand now, the content of the objects are equals but they have different references.
Thank you so much for your help!

**Comment by ajambrovic** [comment]
@yukiofera - Glad I could help :)

**Comment by cagataycivici** [comment]
This is because of;

https://github.com/angular/angular/issues/17685

Thinking of a workaround.

**Comment by cagataycivici** [comment]
Added a workaround but we need the formControl instance so with 4.2.2, you can do;

> Checkbox can be used in a model driven form as well. In this case, due to an issue in Angular bind the formControl instance instead of using formControlName.

```xml
<!-- Wrong -->
<p-checkbox formControlName="cities"></p-checkbox>

<!-- Correct -->
<p-checkbox [formControl]="myFormGroup.get['cities']"></p-checkbox>
```

**Comment by coenraadf** [comment]
Been waiting for this fix for a while.

Just note, your documentation is not 100% correct. What worked for me was:

<p-checkbox [formControl]="myFormGroup.controls['cities']"></p-checkbox>

**Comment by achuou1** [comment]
@coenraadf thanks for pointing out there, documentation is still not updated. ".controls[cities]" works for me also.

**Comment by cagataycivici** [comment]
What works for me is;

```xml
  <div *ngFor="let d of data">
    <p-checkbox [value]="d" [label]="d.text" [formControl]="group.get('chk')" name="chk"></p-checkbox>
  </div>
```

```typescript
constructor(fb: FormBuilder) {
        this.group = fb.group({
          chk: [[]]
        });
      }
```

**Comment by cagataycivici** [comment]
Docs fixed now.

**Comment by talamaska** [comment]
I don't think the suggested workaround is 100% correct. This wouldn't pass AOT building. I thing it should be ```[formControl]="form.get('cities')"```

**Comment by valentin78** [comment]
for me this 
`<p-checkbox [formControl]="myFormGroup.get['cities']"></p-checkbox> `
still not working. Change event not fired and value not tied to control

**Comment by phantomkk** [comment]
form.get('cities')
myFormGroup.controls['cities']"></p-checkbox> 

nothing works for me

**Comment by khaledtamam** [comment]
any update ?

**Comment by antsteyer** [comment]
This is not working with FormArray control

**Comment by theabspro** [comment]
Can anyone post full example please?

**Comment by ProfEibe** [comment]
The current fix does not work anymore because the p-checkboxes formControl field expects a value with the type FormControl. But the ```myFormGroup.controls['cities']``` returns an AbstractControl. Maybe this could be adjusted in the checkbox-component, if it isn'T necessary to be FormControl.

**Comment by avnerma** [comment]
I just figured out, casting is required -
```html
<p-checkbox [formControl]="$any(myFormGroup.controls['cities'])"></p-checkbox>
```
