### ISSUE TITLE
p-tooltip is forever stuck on the page when a hide delay is specified and the tooltip target is hovered again while the tooltip is hiding.

### ISSUE THREAD

**Issue by Giwayume** [primefaces/primeng#3462]
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: NodeJS 6.10.2
- Affected browsers: Chrome

## 2) Expected behavior

The tooltip should not get stuck on the page.

## 3) Actual behavior

The tooltip is getting stuck when hovering over the tooltip target while the tooltip is hiding.

## 4) Steps to reproduce

1. Make a tooltip with a hide delay, a la
`<span pTooltip="Tooltip Text!" showDelay="200" hideDelay="500"><i class="fa fa-question-circle" aria-hidden="true"></i></span>`
2. Hover over the icon to show the tooltip.
3. Move your mouse away from the icon so the tooltip starts to hide, then quickly move the mouse back to hover over the icon again.
4. The tooltip will no longer hide itself, no matter what.

## 5) Sample HTML

`<span pTooltip="Tooltip Text!" showDelay="200" hideDelay="500"><i class="fa fa-question-circle" aria-hidden="true"></i></span>`

**Comment by aervin** [comment]
I had an issue with this as well. I opened a [pull request](https://github.com/primefaces/primeng/pull/3541) with a simple 4-line fix if you want to take a look.

**Comment by cagataycivici** [comment]
Fixed via PR.

**Comment by Ninja-Coding-Git** [comment]
problem persists on 4.1.3

**Comment by tleveque23** [comment]
This should not be closed because the bug still exist on 5.0.2.
Please re-open and fix.
