### ISSUE TITLE
Button support custom icon 

### ISSUE THREAD

**Issue by zealitude** [primefaces/primeng#4588]
### There is no guarantee in receiving a response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeNG PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[x] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**What is the motivation / use case for changing the behavior?**

I want to use my own svg icon instead of font-awesome icon.

suggest to provide a new attribute to button component 
for developer to add custom image path

**Comment by cagataycivici** [comment]
Sounds good, we're likely to do this due to the recent changes on font awesome as well.

**Comment by MikeDabrowski** [comment]
@cagataycivici 
This seems to be related to https://github.com/primefaces/primeng/issues/5098 I'd like to use FA5 icons and keep its tree shaking magic. However swapping icons in menus or btns is not currently possible.
What are the chances you will add an option to inject custom elements with icons ?

**Comment by mickeyjohn** [comment]
Is there any activity to make button support svg icon yet? can anyone suggest in ideas on how to acheive that? Thanks a lot in advance.

**Comment by jbjhjm** [comment]
Any news on this? I'm in with FA5 too.
Think it would be a great plan to add a globally configurated iconProvider helper class which can either distinguish between different icon systems or can be replaced to provide an own rendering system.

**Comment by yelhouti** [comment]
@cagataycivici do you want help by any chance for this?

**Comment by yelhouti** [comment]
here is a workaround/hack tu support fa-icons in the meantime:
```
<p-button [label]="label" icon="true">
    <fa-icon icon="plus" [classes]="['ui-button-icon-left']"></fa-icon>
</p-button>
```
the `icon="true"` is a "lie" that will add a class `true` but activate and deactivate some other classes, the `ui-button-icon-left` should give the correct design/dimensions to the the svg icon, hope it helps someone else.
it also works with icon only

**Comment by bendehghan** [comment]
What @yelhouti says works for buttons. Is there a workaround for menus also?

**Comment by jbjhjm** [comment]
Not that I know of @bendehghan .

## Proposal idea 1 - pass ref

Support element/template references to be passed to icon inputs.
That way one could use both systems:

```html
<ng-template #myIcon><fa-icon icon="something" ></fa-icon></ng-template>
<button pButton [icon]="myIcon"></button>
```

cons: pretty much code to show a icon.

## Proposal idea 2 - support content child

Use @ContentChild('#icon') to find and render icon correctly.

```html
<button pButton icon="my-icon-class">
  <fa-icon icon="something" id="icon"></fa-icon>
</button>
```

cons: not working for input[type=submit].

---

both solutions have one additional weakness: They only work in templates. Any idea how a custom icon element could work with MenuItem Model?

**Comment by projectX21** [comment]
With new v10 it is easier to include custom icons into buttons. I have the following workaround in my project:

```
<button type="button" pButton pRipple class="custom-label">
  <fa-icon icon="bars"></fa-icon>
</button>
```

style.scss:
```
button.p-button.custom-label > span.p-button-label {
  display: none;
}
```

The p-button-label has to be hidden, because otherwise the text '& nbsp;' will be shown. However, if you need a label text, it can be included into the button tag easily:
```
<button type="button" pButton pRipple class="custom-label">
  <fa-icon icon="bars"></fa-icon>
  <span>my own label</span>
</button>
```

Now you can create your own customized label inside the button tag.

**Comment by yigitfindikli** [comment]
Fixed in v10.

**Comment by DeanWilliamMills** [comment]
I am on the latest version and still not working.
Or at least nothing the docs how to use Fontawesome with Prime NG menuBar.

```
this.items = [
  {
    label: 'DASHBOARD',
    icon: 'custom-icon', ///// WHAT COMES HERE???
  },
```

**Comment by yaroslav-craftsoft** [comment]
I would guess that you'll need to define a custom template for the menu item as described [here](https://primeng.org/menu#template) and then use `fa-icon` component inside that template as you would normally do 🤔

**Comment by devoto13** [comment]
If you use [icon library](https://github.com/FortAwesome/angular-fontawesome/blob/main/docs/usage/icon-library.md), I guess you should be able to pass icon name as `icon` property and make use of it in the template. But happy that you're able to solve it!
