### ISSUE TITLE
Table checkbox selection ignores filtering

### ISSUE THREAD

**Issue by coffeymatt** [primefaces/primeng#5220]
**I'm submitting a ...
```
[x ] bug report
```

**Current behavior**
If you use table selection (https://www.primefaces.org/primeng/#/table/selection) and have a checkbox header to select all (p-tableHeaderCheckbox), selecting all will include filtered out rows and rows from other pages.

**Expected behavior**

When you select all, it shouldn't include in the selected data array, data that has been filtered out or is on another page. It should only select what's visible on the screen.

**Minimal reproduction of the problem with instructions**

Create a table with two pages of data and a basic filter and multi row selection with checkboxes as per the docs. Note that when you select all, items you have filtered out or are on another page are included in the selection.

**What is the motivation / use case for changing the behavior?**

It's the logical expected behaviour, only to select what you can see.

* **Angular version:** 5.2.6

* **PrimeNG version:** 5.2.0

* **Browser:** all
 
* **Language:** [all]

**Comment by mousedown** [comment]
+1

**Comment by mhaisley** [comment]
Having the exact same issue. 
Is there a temporary fix that can be implemented with table selection?

**Comment by mousedown** [comment]
You would have to keep track of the current filters selected with onFilter() then manually remove them from the array set with `[(selection)]=`

**Comment by arjendevries** [comment]
I'm having a similar issue.  When I check  the p-tableHeaderCheckbox I get all on page (in my case 20) and next i nav through pages I can select one off items and it adds to my total number of selected items.  However as soon as I check the select all on page again it blows away my selected items and shows me only those 20.  Same thing if i select all on page 1, go to page 2 and select all again...page 1 stuff is gone.

**Comment by zillog** [comment]
Same behavioral issues here ... totally confusing feature if it does not work fully integrated with paging and filters.

**Comment by mousedown** [comment]
Anyone confirmed this in 5.2.4? The select all  checkbox is now not responding for me.

**Comment by chfiras** [comment]
it's fixed in 5.2.4

**Comment by chfiras** [comment]
after filtering and select all with checkbox you cannot deselect  all with the checkbox again
that issue appear in the version 5.2.4

**Comment by e01010100** [comment]
In 5.2.4 the behavior appears to be different depending on if `[headerCheckboxToggleAllPages]` is `"true"` or `"false"`. If true then the bug is still there and the check-all checkbox ignores filtering. If false, then the check-all checkbox appears to work correctly (clearing previously selected options and selecting all currently filtered options). 

However, I am using the deprecated datatable: https://www.primefaces.org/primeng/#/datatable/selection

**Comment by Darnoj** [comment]
What should be the behaviour for the following situation :

1. Select 4 rows
2. Filter to display only 2 of the 4 rows selected
3. => the 2 hidden rows should remain selected or not ?

**Comment by chfiras** [comment]
the 2 hidden rows not selected

**Comment by Darnoj** [comment]
@chfiras p-table keep the selection, no matter what is filtered

**Comment by e01010100** [comment]
> What should be the behaviour for the following situation :
>    Select 4 rows
>    Filter to display only 2 of the 4 rows selected
>    => the 2 hidden rows should remain selected or not ?

In that case the 4 rows should remain selected as you took no extra action. 

1. Select All rows (4)
2. Filter to display only two rows (both of which are still selected, including the two you can no longer see)
3. Deselect all rows (0 now selected)
4. Select all rows while filtering is still applied (2 rows selected)
5. Clear filtering - all rows now shown (2 rows still selected)

**Comment by mousedown** [comment]
>  you took no extra action


So the p-table doesn't actually maintain the selection. The component needs to keep track when 'select all' checkbox is applied, then deselect all, then select all programatically when the filter changes with via onFilter

I presumed the table would respect the filtering

**Comment by NetliDev** [comment]
I handled it using **this.dataSource.filteredData**  instead of **this.dataSource.data**.
