### ISSUE TITLE
Turbo table with frozen columns and scrollbar overlaps paginator

### ISSUE THREAD

**Issue by JacobSiegle** [primefaces/primeng#5566]
```
[X] bug report
```

**Plunkr Case (Bug Reports)**
http://plnkr.co/edit/fONzXkXqyLp2pPOf5jEF?p=preview

**Current behavior**
The table bottom row overlaps the paginator.

**Expected behavior**
The table bottom row should align like PrimeNG 5.2.3.
NOTE: PrimeNG 5.2.3 does not align properly on Firefox.

**Minimal reproduction of the problem with instructions**
View plunker.

**What is the motivation / use case for changing the behavior?**
Bug fix.

**Comment by cagataycivici** [comment]
Fixed in 5.2.4.

**Comment by JacobSiegle** [comment]
Not patched on 5.2.5. Scroll bar appears over paginator on edge, FF, and chrome.

Plunker seems broken now, so I created a stackblitz -
https://stackblitz.com/edit/github-jd3niz

**Comment by olingerc** [comment]
Hi,

I'm on the latest version 8.1.1 and I still have this issue.


This is how I create the table
```html
<p-table
    id="samplesTable"
    #dataTable
    [value]="samples"
    sortMode="multiple"
    [multiSortMeta]="multiSortMeta"
    [scrollable]="true"
    scrollHeight="420px"
    selectionMode="single"

    rows="200"
    [lazy]="true"
    [paginator]="true"
    (onLazyLoad)="loadSamplesLazy($event)"
    [totalRecords]="totalSamples"
    columnResizeMode="expand"
    [alwaysShowPaginator]="false"
    [rowHover]="true"
    dataKey="OrderId"
    [virtualScroll]="false"
    trackBy="trackOrders"
    frozenWidth="138px"
    >

    <ng-template pTemplate="frozenheader">
      <tr>
        <th class="orderStatus"></th>
...
      </tr>
    </ng-template>
    <ng-template pTemplate="frozenbody" let-rowData>
      <tr>
...
      </tr>
    </ng-template>

    <ng-template pTemplate="header" let-columns>
      <tr>
...
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-rowData>
      <tr>
...
      </tr>
    </ng-template>
    <ng-template pTemplate="emptymessage">
      <tr>
...
      </tr>
    </ng-template>
  </p-table>
```

This is a screenshot
![image](https://user-images.githubusercontent.com/5046645/68875362-ffbb1080-0702-11ea-83cf-6ff5abb5f160.png)

**Comment by tiagolisalves** [comment]
@olingerc Same here, this issue should be reopened.
