### ISSUE TITLE
Schedule not working on Angular 6 prod mode

### ISSUE THREAD

**Issue by elias-garcia** [primefaces/primeng#5724]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
In Angular 6 production mode (after running ng build --prod) and using Lazy Loading routes, the schedule is not rendering, but in development mode (ng serve) it's working as expected. This happens only on Angular 6, on 5.2 was working fine.

**Expected behavior**
The schedule should render and call the onViewRender event.

**Minimal reproduction of the problem with instructions**
Create a component `Schedule.component` with the cli and only put the `<p-schedule></p-schedule>` inside it's HTML. Then, lazy load it in the `AppModule` for example and run the `ng build --prod` script. After it, serve the distribution file and see it behavior.

**Please tell us about your environment:**

macOS 10.13.4
VSCode 1.23.1
npm 5.6.0

* **Angular version:** 6.0.0

* **PrimeNG version:** 5.2.6

* **Browser:** all

 
* **Language:** TypeScript 2.7.2

* **Node (for AoT issues):** `node --version` =   9.11.1

**Comment by luisabreu** [comment]
Some problem here. I've reported it here too: https://github.com/primefaces/primeng/issues/5717

**Comment by cagataycivici** [comment]
https://github.com/primefaces/primeng/issues/5717

**Comment by hle09** [comment]
I've fixed this problem by **NOT** using the min version of moment.js and fullcalendar.js. 
New scripts section in .angular-cli.json or angular.json depending on CLI version:
"scripts": [
	    "../node_modules/jquery/dist/_**jquery.slim.js**_",
	    "../node_modules/moment/_**moment.js**_",
	    "../node_modules/chart.js/dist/Chart.js",	    
        "../node_modules/fullcalendar/dist/_**fullcalendar**.js_"
	    ],

As opposed to the old one:
      "scripts": [
	    "../node_modules/jquery/dist/_**jquery.js**_",
	    "../node_modules/moment/min/_**moment.min.js**_",
	    "../node_modules/chart.js/dist/Chart.js",	    
        "../node_modules/fullcalendar/dist/_**fullcalendar.min.js**_"
	    ],

Hope this helps.

**Comment by elias-garcia** [comment]
Thanks for the response @hle09, your solution is working fine as using min versions still doesn't work... @cagataycivici
