### ISSUE TITLE
Dialog in IOS Devices Bug When Scroll Screen

### ISSUE THREAD

**Issue by pedrotcm** [primefaces/primeng#5828]
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Bug Report**
The bug occurs in primeng's own showcase.
https://www.primefaces.org/primeng/#/dialog
Follow video for easy viewing: https://drive.google.com/file/d/16CDfb2mh0cO3xCFqoZIKQkye9dyW52kd/view

**Current behavior**
When you open and close the dialog and then slide the screen to the url of the browser disappears, when you click to open the dialog again it goes off alone and the screen is as if it had overlay.

**Expected behavior**
The dialog should open normally.

**Minimal reproduction of the problem with instructions**
1. Access the showcase for an IOS device and click on the page to open the dialog.
2. Close the dialog.
3. Slide the top of the browser url away.
4. Click to open the dialog.

**What is the motivation / use case for changing the behavior?**
The functionality of the dialog is essential if it works correctly.

**Please tell us about your environment:**

* **Angular version:** 6.0.2

* **PrimeNG version:** 5.2.7

* **Browser:** [ IOS Mobile Chrome |  iOS Safari  ]

* **Node (for AoT issues):** `node --version` =   8.11.2

**Comment by pedrotcm** [comment]
Any feedback for this bug?

**Comment by pedrotcm** [comment]
The bug is still on PrimeNG 6.0.0-rc.1.

**Comment by rafa-as** [comment]
Same here!

**Comment by bbuehrer** [comment]
I just noticed the same problem on IOS, but without scrolling!
I open a dialog the first time and it appears.
If I then close the dialog and open it again, it disappears immediately and the window is not operable. Everything works perfectly well in android.

**Comment by dinohorvat** [comment]
+1, the bug is also present on OSX but after you drag the dialog or resize the screen.

https://github.com/primefaces/primeng/issues/5949

**Comment by egedarcin** [comment]
can you guys also tell the iOS versions of your devices?

**Comment by dinohorvat** [comment]
@egedarcin I'm facing the same problem on macOS

macOS High Sierra 10.13.3
Safari Version 11.0.3

**Comment by bbuehrer** [comment]
IPhone 5 with IOS 11 (current version).

**Comment by dinohorvat** [comment]
I also tested it on iPhone 8 Plus (iOS 11.4.1), and it works fine. So for me the only problem is macOS

**Comment by pedrotcm** [comment]
Iphone 6 Plus (iOS 11.4)

**Comment by cagataycivici** [comment]
6.1.1 should fix it when [blockScroll]="true", if not drop a comment we'll reopen.

**Comment by bbuehrer** [comment]
This is not the solution! I already had [blockscroll]="true" and the problem still occurs ...
