### ISSUE TITLE
Calendar month and year navigator dropdowns not binding to backing store

### ISSUE THREAD

**Issue by kallidean** [primefaces/primeng#6209]
You can see and reproduce this behavior right on the primeNG demo site.
https://www.primefaces.org/primeng/#/calendar

Steps:
Click on the navigators example
Paste or type a past date ("01/01/2017")
Click off the control to close the overlay panel
Click back on the date and see the overlay panel still displaying current month/year (regardless of selected value)
Select an alternate date on the overlay panel (notice the newly selected date stays in the currently selected month/year, but the dropdowns still show current month/year)

<img src="https://image.ibb.co/mgE8Dz/p_Calendar.jpg"/>

**Comment by opetriienko** [comment]
+1

**Comment by JacobSiegle** [comment]
Seems fixed in the latest build?

**Comment by kallidean** [comment]
Still broken on the public demo website.  If fixed, when will it be in a versioned release?

**Comment by oliverfrost** [comment]
Just in case one more way to reproduce the issue (PrimeNg v.6.1): https://stackblitz.com/edit/github-uggfuf

**Comment by kallidean** [comment]
Fixed as of 6.1.0, thanks guys!

**Comment by oliverfrost** [comment]
@kallidean, are you sure? Check out my template. It`s running version 6.1.0 and there is still something wrong with synchronization between calendar and month navigator.

**Comment by kijosis** [comment]
Still broke for me.

**Comment by cagataycivici** [comment]
Fixed at #6261
