### ISSUE TITLE
[Bug] Error trying to use angular 8, bad path import in table.ts

### ISSUE THREAD

**Issue by jmesa-sistel** [primefaces/primeng#7355]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**

If you try to compile an app using last angular 8 (beta7 in this case) you will get an error

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Compile an app which use a **p-table** using angular 8 beta 7
you will get the next error: 
`ERROR in node_modules/primeng/components/table/table.d.ts(5,27): error TS2307: Cannot find module '@angular/core/src/metadata/lifecycle_hooks'.`

**What is the motivation / use case for changing the behavior?**

Fix a future bug in angular 8

* **Angular version:** 

Angular 8 beta 7

* **PrimeNG version:** 

PrimeNG:  7.1.0-rc.1

The bug is in table.ts:

```
import { NgModule, Component, HostListener, OnInit, AfterViewInit, AfterViewChecked, Directive, Optional, AfterContentInit, Input, Output, EventEmitter, ElementRef, ContentChildren, TemplateRef, QueryList, ViewChild, NgZone, EmbeddedViewRef, ViewContainerRef} from '@angular/core';
.....
import { OnDestroy } from '@angular/core/src/metadata/lifecycle_hooks';
.....
```

The OnDestroy import has to be in '@angular/core'

**Comment by JacobSiegle** [comment]
PrimeNG hasn't had a compatible release for Angular 8 yet.

**Comment by jmesa-sistel** [comment]
@JacobSiegle
Primeng is working perfectly in Angular 8 beta 7 after that change. Ivy not enabled.

**Comment by Mysame** [comment]
It's a bad import that should be fixed regardless.

**Comment by jbedard** [comment]
Also running into this issue. There would be no harm fixing this, even before any angular 8 support...

**Comment by coreboarder** [comment]
This strikes me as an easy fix no?

Line **5** in **primeng/components/table/table.d.ts** change 
- "import { OnDestroy } from '_@angular/core/src/metadata/lifecycle_hooks_';"
 to 
- "import { OnDestroy } from '_@angular/core_';"

**Comment by JacobSiegle** [comment]
It probably is. I don't use angular 8 yet but if you do you can test/PR it and i'm sure they will accept. Otherwise I assume it will be fixed when the official 8 release is out.

**Comment by cagataycivici** [comment]
Angular 8 is not out yet so closing.

**Comment by jmesa-sistel** [comment]
@cagataycivici 
Not yet, but the import is wrong anyway.
`import { OnDestroy } from '@angular/core/src/metadata/lifecycle_hooks';`
is wrong, It's a bad import that should be fixed

**Comment by kartik468** [comment]
@cagataycivici Angular 8 is now live.
Issue still exists.
I can see the commit 97ffa3fb902598044442e8dcb377e65b0e6729b0 (fixed #7627 Support Angular 8)
Its not part of latest release i.e. 7.1.3

**Comment by JanST123** [comment]
+1

Please update npm package

**Comment by satheeshhb** [comment]
Just upgraded my application to Angular 8 from 7. I upgraded primeng version to latest version 7.1.3, but still i am facing the issue.

**Comment by dima716** [comment]
Also facing the issue

**Comment by jasperbosch** [comment]
+1

**Comment by armved** [comment]
+1

**Comment by dmytro-gokun** [comment]
Please make a minor release with the fix, so everybody can start using Angular 8. It looks like primeng is a showstopper for many people.

**Comment by thackerc** [comment]
@cagataycivici Can you reopen this issue not that Angular 8 is out and this is still a problem?

**Comment by jmesa-sistel** [comment]
@thackerc Primeng 8.0.0-rc.1 is out with this bug fixed but you will find other bugs.
See [#7769](https://github.com/primefaces/primeng/issues/7769)

**Comment by pppdns** [comment]
it's still not fixed in `7.1.3`, which is the latest minor version in version 7. Is there a time estimate for it? Or did PrimeNG already cut support for any version below 8.0.0 (which is only one week old)?

The change should be as simple as changing 2 lines.

Maybe simply `git cherry-pick` 97ffa3f after 7.1.3 and release it as 7.1.4?

Thanks a lot in advance @cagataycivici and let me know how I can help

**Comment by danielsmeyer** [comment]
Fixed in the 8.0.0 release.

**Comment by pppdns** [comment]
Thanks. And what about 7.x versions? Did PrimeNG already end official support for 7.x?

Angular 8 doesn't work with PrimeNG 7 because of this one small import issue which should only require 2 lines of change. It's not an immediate option for many apps to just upgrade to PrimeNG 8.0.0 as it has a lot of breaking changes (despite the official docs).

This is a show stopper for many apps, PrimeNG 7.1.3, which is the latest of version 7 and which is only one month, doesn't work with Angular 8. A minor bugfix version could be released at least for PrimeNG v7, this bug really isn't related to Angular 8 at all, it's simply a bad import path.

It's sad to see that only the lastest PrimeNG version is supported, which is 2 weeks old, many other tools support older versions for 1-2 years at least, but really not for just a few weeks.

**Comment by jmesa-sistel** [comment]
@pppdns breaking changes? There is only a very few little changes. Have you read the changes?
[https://github.com/primefaces/primeng/blob/master/CHANGELOG.md](https://github.com/primefaces/primeng/blob/master/CHANGELOG.md)

**Comment by pppdns** [comment]
yes, for example `Remove DataTable #7759` is not listed as a breaking change, even though it breaks a lot of codebases that use this (previously deprecated) component. Deprecating a feature is no breaking change, but removing the feature is

**Comment by orhemi** [comment]
@jmesa-sistel There is any intention to add that fix to 7 version too? 
For those who are not interested in upgrading to v8

**Comment by sgentile** [comment]
please fix angular 8 is out

**Comment by shorstki** [comment]
Why this is closed? Same issue here

**Comment by shubhamtakode** [comment]
Please fix this issue.

**Comment by blackstrings** [comment]
as stated in https://github.com/primefaces/primeng/issues/7769, anyone on or upgrading to Angular 8, should use primeng version 8 and install the following dependency chart.js and quill and don't forget to add the two scripts into the angular.json
