### ISSUE TITLE
Table does not reset page on filter

### ISSUE THREAD

**Issue by chauf** [primefaces/primeng#7453]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please see PR.

**Current behavior**
If one stays on page two in a primeng table and changes a filter to a value where only results for one page are returned the table will be empty and page selector is in an incorrect state.

**Expected behavior**
If one stays on page two in a primeng table and changes a filter the current active page should always be rest two the first page.

**Minimal reproduction of the problem with instructions**
* Open a filtered and paged table.
* Select any Page > 1
* Change any Filter to return  less Results then the page you selected

**Angular version:** 7.1.4

**PrimeNG version:** 7.1.1-SNAPSHOT

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by chauf** [comment]
Please find a possible fix in https://github.com/primefaces/primeng/pull/7454

**Comment by cagataycivici** [comment]
Works for me at;

https://www.primefaces.org/primeng/#/table/filter

How to replicate.

**Comment by chauf** [comment]
This would only happen if the table is in lazy mode.

**Comment by cagataycivici** [comment]
#7437 should fix this

**Comment by clpalmer** [comment]
@cagataycivici - This issue is not fixed for me. I have the same problem. I have a table using lazy loading and with filters and pagination. If I change to page 2 and then apply a filter that results in <1 page of results, lazy load gets called with first still set to the 2nd page and it returns 0 results. The paginator then seems to return to page 1, but the lazy load method isn't called again so the table remains with 0 results.

The fix in #7454 from @chauf fixes the issue for me.

**Comment by andriikuts** [comment]
+1

**Comment by NekitCorp** [comment]
When filtering, call **onLazyLoad** earlier than the reset **first**
call **onLazyLoad**: https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L1184
reset **first**: https://github.com/primefaces/primeng/blob/master/src/app/components/table/table.ts#L1282

**Comment by acoroza** [comment]
I still have trouble with this one. You cannot differentiate `onLazyLoad` events if it was emitted by filtering or by changing the page.

**Comment by earshinov** [comment]
@acoroza , you can reset page number right when you apply the filter:

```
// A helper method to be called instead of table.filter
function filterTable(...) {
  // Forcefully switch to first page
  // https://github.com/primefaces/primeng/issues/7453
  table.first = 0;

  return table.filter(value, field, matchMode);
}
```

That's how we do it.

**Comment by acoroza** [comment]
@earshinov I have something like `(onLazyLoad)="loadSuburbs($event)"` which is always called whenever you do a `filter` or `sort`. I can always set the page to page 1 by using `this.suburbsTable.first = 0;` and it works fine. The problem is `(onLazyLoad)` gets emitted when you change the page. What happens is page will go back to 1 when you click page 2(or 3 or 4 and so on). There is no way to determine if the `onLazyLoad` event was emitted via filtering, sorting, or via page change.

**Comment by earshinov** [comment]
@acoroza , I got it from your first message. My advice is to reset the page when you filter rather than when you load. It works for us and I don't yet see a reason why it can't work for you. Hope my advice helps.
