### ISSUE TITLE
Upgrading to Primeng 1.0.0-beta.13 -- now I get --  Can't bind to 'pTemplateWrapper' since it isn't a known property of 'template'"'y

### ISSUE THREAD

**Issue by JakeSummers** [primefaces/primeng#762]
Full error:

```
Template parse errors:
Can't bind to 'pTemplateWrapper' since it isn't a known property of 'template'. ("an *ngIf="!itemTemplate">{{option.label}}</span>
                    <template *ngIf="itemTemplate" [ERROR ->][pTemplateWrapper]="itemTemplate" [item]="option"></template>
                </li>
            </ul>"): Listbox@7:51
Can't bind to 'item' since it isn't a known property of 'template'. ("label}}</span>
                    <template *ngIf="itemTemplate" [pTemplateWrapper]="itemTemplate" [ERROR ->][item]="option"></template>
                </li>
            </ul>
"): Listbox@7:85
Property binding pTemplateWrapper not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("tion)">
                    <span *ngIf="!itemTemplate">{{option.label}}</span>
                    [ERROR ->]<template *ngIf="itemTemplate" [pTemplateWrapper]="itemTemplate" [item]="option"></template>
        "): Listbox@7:20
Property binding item not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("tion)">
                    <span *ngIf="!itemTemplate">{{option.label}}</span>
                    [ERROR ->]<template *ngIf="itemTemplate" [pTemplateWrapper]="itemTemplate" [item]="option"></template>
        "): Listbox@7:20
```

Upgraded from: 

```
  "dependencies": {
    ...
    "primeng": "1.0.0-beta.12",
    "primeui": "4.1.14",
    ...
  },
```

To: 

```
  "dependencies": {
    ...
    "primeng": "1.0.0-beta.13",
    "primeui": "4.1.15",
    ...
  },
```

Not sure if this is a bug, however it looks like the [Listbox](https://github.com/primefaces/primeng/blob/master/components/listbox/listbox.ts) component, *may* be missing a directive to the [TemplateWrapper](https://github.com/primefaces/primeng/blob/master/components/common/shared.ts).  

I think that this commit 23ac61b90ea26ad527858e58b038cca6b958c832 may have introduced the regression.  

Thanks!
Jake

**Comment by JakeSummers** [comment]
I suspect that this issue may be caused by the changes to use `@NgModule`.

See:

https://docs.google.com/document/u/1/d/1isijHlib4fnukj-UxX5X1eWdUar6UkiGKPDFlOuNy1U/pub

**Comment by yazari-fa** [comment]
I have the same issue using angular class's angular2-webpack-starter and primeng 1.0.0-beta.12.

**Comment by cesarrew** [comment]
Same issue when moved to Webpack, following this guide in angular.io: https://angular.io/docs/ts/latest/guide/webpack.html.

The issue occurs only with the production build.

**Comment by JakeSummers** [comment]
Fixed this issue two weeks ago but made a lot of changes and didn't ever pinpoint exactly what the issue was.  Going to close this issue.

**Comment by ernaone** [comment]
Still have the same error when i upgraded to 
 "dependencies": {
    ...
    "primeng": "1.0.0-beta.15",
    "primeui": "4.1.15",
    ...
  },

And switched to webpack.
