### ISSUE TITLE
KeyFilter is not working

### ISSUE THREAD

**Issue by shaileshyadav24** [primefaces/primeng#7729]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Paste is not working

**Expected behavior**
Paste should work.

* **Angular version:** 7.2

* **PrimeNG version:** 7.1.3

Validated this code is not giving proper response:
   @HostListener('paste', ['$event'])
    onPaste(e) {
        const clipboardData = e.clipboardData || (<any>window).clipboardData.getData('text');
        if (clipboardData) {
            const pastedText = clipboardData;
            if (!this.regex.test(pastedText)) {
                e.preventDefault();
            }
        }

**Comment by JACrazy** [comment]
Yes, the code is testing the clipboard data improperly. [See my comment here for how this can be fixed](https://github.com/primefaces/primeng/issues/4850#issuecomment-497062848)

**Comment by JACrazy** [comment]
That commit will still not fix the issue with properly validating the regex of the pasted text. It will allow illegal characters as long as one character exists that passes the regex.test().

**Comment by sonyshankar2k** [comment]
JACrazy, Have you tried it in prime ng 8.0.3? cagataycivici, Is this fixed in prime ng 8.0.3?

**Comment by JACrazy** [comment]
I haven't tested on 8.0.3 but just by viewing the code that is on git, you can see it is still broken with validating pasting. The component hasnt been modified since 2 months ago.

**Comment by sonyshankar2k** [comment]
Thank you so much JACrazy
