### ISSUE TITLE
Dropdown is not align with input when using appendTo="body" property

### ISSUE THREAD

**Issue by NathanAlcantara** [primefaces/primeng#7808]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

https://stackblitz.com/edit/github-mcc3mc-dkrdpx

**Current behavior**
When autocomplete is inside a modal and using `appendTo='body'` the suggestions appears not align with the input

**Expected behavior**
Suggestions and input should be align with each other

**Minimal reproduction of the problem with instructions**
Open dialog and see the difference of a autocomplete with `appendTo` and without

**What is the motivation / use case for changing the behavior?**
Once a autocomplete is inside a dialog, suggestions appear on dialog and the scroll is show up just to see the suggestions, i belive that isn't a the best behavior, and i need that suggestions appears out of dialog

The problem is kind of similiar at this issue: #6918

**Please tell us about your environment:**

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [Chrome XX | Firefox XX]
 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =   v10.13.0

**Comment by sidneibiz** [comment]
+1

**Comment by csvinhal** [comment]
+1

**Comment by elizeugba** [comment]
+1

**Comment by nandhini0612** [comment]
I too facing this issue but I can't find any solution what is the solution for this

**Comment by HangZhouWan** [comment]
I too facing this issue but I can't find any solution what is the solution for this. In which version it is fixed @yigitfindikli, can you take a look on this bug?

**Comment by EzePerucca** [comment]
![image](https://user-images.githubusercontent.com/39660083/129795513-f2c902e6-e57e-4040-9ec6-8464e369d2ba.png)
Still happening, can´t find a way to fix it yet

**Comment by purrfectdoodle** [comment]
Currently facing this issue while using PrimeNg 8.1.4.
