### ISSUE TITLE
DropDown onChange not firing when using keyboard arrows

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#808]
Changing the selection on a DropDown using the keyboard does not fire the onChange event.

**Comment by caebeman** [comment]
Which verison of primeng are you using? This appears to have been fixed in beta 12

**Comment by cagataycivici** [comment]
Shoud be fixed in recent releases, please drop a comment if issue still persists and we may reopen.

**Comment by kadosh1000** [comment]
The issue still persists. I am having the same issue using version 4.1.2
