### ISSUE TITLE
Chrome doesn't respect the autocomplete property of the p-autocomplete component

### ISSUE THREAD

**Issue by francovegini** [primefaces/primeng#8096]
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
The p-autocomplete component has the autocomplete attribute set to _off_ by default. However, even with this value, Google Chrome's autocompletion is still displayed, causing the problem shown in the third image (Chrome's autocompletion appears over the component list).

![inspect_element](https://user-images.githubusercontent.com/31110660/63772321-3d03c500-c8af-11e9-8b71-62547433ebfd.png)

![chrome_autofill](https://user-images.githubusercontent.com/31110660/63772324-3ecd8880-c8af-11e9-9566-db794b034f8e.png)

![image](https://user-images.githubusercontent.com/31110660/63773469-9a991100-c8b1-11e9-811e-ab3c325f3739.png)

**Expected behavior**
The expected behavior is Google Chrome's autocompletion not being displayed, but after some research, I found out that Chrome ignores the autocomplete property when it is set to "off".

To fix this, I created a new @input in the p-autocomplete component and associated the autocomplete HTML property with it, in a way that the developer is able to send a value that actually disables Chrome's autocompletion.

Please take a look at PR #8097

**References:**
https://stackoverflow.com/questions/15738259/disabling-chrome-autofill
https://bugs.chromium.org/p/chromium/issues/detail?id=370363#c7

* **Angular version:** 7.X

* **PrimeNG version:** 7.X

* **Browser:** [Chrome]

* **Language:** [all]

**Comment by csvinhal** [comment]
+1

**Comment by sidneibiz** [comment]
+1

**Comment by falexandre** [comment]
+1

**Comment by hemanuelx** [comment]
+1

**Comment by philipstefan** [comment]
+1

**Comment by yigitfindikli** [comment]
Fixed in https://github.com/primefaces/primeng/commit/f539e1bac75c18337f6ad77f19a017a9e271458a

**Comment by lazovic6** [comment]
I think I have a solution for autocomplete, since it still doesn't work. As of 2018, you have to change autocomplete="new-password" instead of autocomplete="off" for it to work (autocomplete="off" doesn't work any more). Checked it, changed it in my project and it works. Hope you will fix this soon

**Comment by StruninIhor** [comment]
Still not fixed, prime-ng 11.4.2

**Comment by jacekzwroclawia** [comment]
+ 1
