### ISSUE TITLE
[Bug] Carousel displays last page when circular=true

### ISSUE THREAD

**Issue by vkappie** [primefaces/primeng#8739]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request 
[ ] support request
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/angular-h9hpp3

**Current behavior**
if items set on component load (items is set during ngAfterContentInit) carousel displays the last page, though dots are correct
![image](https://user-images.githubusercontent.com/6415884/79155831-f9d57280-7dfb-11ea-9a1d-d24fb4d660de.png)
If you set items with some delay issue isn't reproduced

PrimeNG Version: 9.0.5
Angular Version: 9.1.1

I've tried 9.0.2 and it works fine

**Expected behavior**
Carousel displays first page
![image](https://user-images.githubusercontent.com/6415884/79155859-01951700-7dfc-11ea-8913-92ff9808cf33.png)

**Comment by vkappie** [comment]
Could be related to #8705

**Comment by fcostazini** [comment]
Hi! will this be fixed in version 9 also?

**Comment by Xriuk** [comment]
Is it really fixed? On 13.2.1 I'm still having this issue, the last page gets shown first and indicator is not working.
As soon as you scroll past the last item of the last page everything works correctly.
What is weird is that even if I set `[circular]="false"` it displays nothing.
Apparently it has something to do with the number of items, I have `[numVisible]="3" [numScroll]="1"` and totally I have 12 items, if I set `numScroll` to 2 or 3 it works, but with 1 it does not
