### ISSUE TITLE
Bug in confirmation dialog

### ISSUE THREAD

**Issue by wallysoncarvalho** [primefaces/primeng#8932]
I'm having some problem with CONFIRMATION DIALOG component after I build the project. It just stays really bugged, the background doesn't show up, only the confirmation element.
The weird thing is that it works perfectly in development. 
So I went to the element in development mode and noticed that the following classes are not being applied after the build:

**`ng-star-inserted ui-widget-overlay ui-dialog-mask ui-dialog-visible ui-dialog-mask-scrollblocker`.**

While inspecting the built project, if I insert these classes in the \<div\> element just below the element \<p-confirmdialog\> it works.

[COMMIT WHERE I'M USING IT](https://github.com/wallysoncarvalho/mgc-web/commit/1d356ccf1be3eaa38d80c0f3d4a08c573b5d325c)

**Current behavior**
Confirm dialog background not showing up !

**Please tell us about your environment:**
Windows 10

* **Angular version:** 9

* **PrimeNG version:** 9.1.0

* **Browser:** Chrome
 
* **Node (for AoT issues):** `node --version` =  10.15.0

**Comment by DebuggerAK** [comment]
BUG 2: acceptLabel, rejectLabel etc. do not work any more...

**Comment by wallysoncarvalho** [comment]
Maybe something with [this function](https://github.com/primefaces/primeng/tree/master/src/app/components/confirmdialog#L333) ??

**Comment by DebuggerAK** [comment]
The complete footer-template-part is not called for option replaces. Example: acceptLabel: 'test' -> option('acceptLabel') will return 'Yes'

**Comment by MykhailoIskiv** [comment]
Not sure about real cause of the issue, but it reproduces when ivy is enabled.
To make it work, as quick fix, one should [disable ivy](https://angular.io/guide/ivy#opting-out-of-ivy-in-version-9) or enable [prod mode](https://angular.io/guide/deployment#enable-runtime-production-mode)

Similar issue is reported in https://github.com/primefaces/primeng/issues/8823 and https://github.com/primefaces/primeng/issues/8724

Also I've noticed that ivy is disabled for[ primeng by default.](https://github.com/primefaces/primeng/blob/master/tsconfig.app.json) Although they might enable it during a build of showcase

**Comment by antsteyer** [comment]
The issue is still here on 10.0.0.rc1, in showcase

**Comment by MiRush94** [comment]
if an application uses Ivy then the fix shouldn't be disabling it, but fixing the dialog itself. Ivy is enabled for a reason.

**Comment by MiRush94** [comment]
Any progress on this bug? Will this be fixed for previous versions? Or is there going to be a workarounf?

**Comment by MykhailoIskiv** [comment]
> Any progress on this bug? Will this be fixed for previous versions? Or is there going to be a workaround?

@MiRush94 as I've mentioned above
I've fixed it for my project by enabling production for all my builds, although it's not very convenient

**Comment by MiRush94** [comment]
yeah that doesn't really work for me, I was hoping for a fix from primeNG itself :S

**Comment by wallysoncarvalho** [comment]
I've stopped the project for a while after I reported this. I still can't believe that after so many people reporting the same problem it still hasn't been fixed.

**Comment by MiRush94** [comment]
> I've stopped the project for a while after I reported this. I still can't believe that after so many people reporting the same problem it still hasn't been fixed.

Yeah it is quiet a shame...

**Comment by waratah** [comment]
duplicate of https://github.com/primefaces/primeng/issues/5090

**Comment by yigitfindikli** [comment]
Unable to replicate with PrimeNG 11.0.0-rc.1, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.

**Comment by mittal-sahab-sudo** [comment]
Any fix for this issue ? Having this issue in primeng 16.0.2
