### ISSUE TITLE
[p-tree] should not select node on right click if contextMenu is set

### ISSUE THREAD

**Issue by guitarooman14** [primefaces/primeng#9520]
**I'm submitting a ...**

[ x ] bug report 
[ ] feature request 
[ ] support request 

**Current behavior**

1. Expand all nodes.
2. Select one leaf in any node.
3. Right click on another node and take a look to the selected node you see compared to
one given by selectionChange event value.
4. If you click away from the contextMenu you will see the previous selected node still selected.

**Expected behavior**

I expect that even when the contextMenu is on, the right click should not select any node like when the contextMenu is not set.

Minimal reproduction of the problem with instructions
https://primeng-tree-with-context-menu-demo.stackblitz.io/

* **Angular version:** 10.0.14

* **PrimeNG version:**  10.0.3

**Possible solution**
Let's see the triggered method when right click a node:

```
 onNodeRightClick(event: MouseEvent, node: TreeNode) {
        if (this.contextMenu) {
           let eventTarget = (<Element> event.target);

           if (eventTarget.className && eventTarget.className.indexOf('p-tree-toggler') === 0) {
                return;
            }
            else {
                let index = this.findIndexInSelection(node);
                let selected = (index >= 0);

                if (!selected) {
                    if (this.isSingleSelectionMode())
                        this.selectionChange.emit(node);
                    else
                        this.selectionChange.emit([node]);
                }

                this.contextMenu.show(event);
                this.onNodeContextMenuSelect.emit({originalEvent: event, node: node});
            }
        }
    }
```

I suggest to remove the following part into the first else:

```
let index = this.findIndexInSelection(node);
let selected = (index >= 0);

if(!selected) {
    if (this.isSingleSelectionMode())
        this.selectionChange.emit(node);
    else
        this.selectionChange.emit([node]);
}
```

**Comment by guitarooman14** [comment]
up

**Comment by davudk** [comment]
I am also having this issue. I see an inconsistency in the way the `onNodeSelected` event is triggered.

When you left click on a tree node, two things happen:
1. the selection changes
2. the `onNodeSelected` event is raised

However, when a context menu is attached to the tree and you right click on a tree node:
1. the selection changes
2. the `onNodeSelected` event is **NOT** raised

This inconsistency should be resolved, either by:
* not changing the selection on a right click (as @guitarooman14 suggests)
* or, by raising the `onNodeSelected` event when a right click occurs on a tree node (i.e. to show the context menu which is attached to the tree)

Angular 11.0.9 / primeng 11.2.0

**Comment by guitarooman14** [comment]
I feel less lonely ^^.

**Comment by matusko89** [comment]
> I am also having this issue. I see an inconsistency in the way the `onNodeSelected` event is triggered.
> 
> When you left click on a tree node, two things happen:
> 
> 1. the selection changes
> 2. the `onNodeSelected` event is raised
> 
> However, when a context menu is attached to the tree and you right click on a tree node:
> 
> 1. the selection changes
> 2. the `onNodeSelected` event is **NOT** raised
> 
> This inconsistency should be resolved, either by:
> 
> * not changing the selection on a right click (as @guitarooman14 suggests)
> * or, by raising the `onNodeSelected` event when a right click occurs on a tree node (i.e. to show the context menu which is attached to the tree)
> 
> Angular 11.0.9 / primeng 11.2.0

I second this

**Comment by davudk** [comment]
Even though the `onNodeSelected` event is not raised in the second case I mentioned above, one can still detect that the selection has changed by attaching a listener on `selection` attribute like this:

```html
<p-tree [value]="treeNodes"
        selectionMode="single"
        [selection]="selectedNode"
        (selectionChange)="setSelectedNode($event)"></p-tree>
```

This is a good workaround. But the downside of this approach is that you can't capture event that was raised, unlike the `onNodeSelected` event which has provides access to `originalEvent: Event`.

This should be fixed. A potential us case is if you want to show a confirmation popup over the tree node to confirm an action which you chose in the context menu (e.g. user selects context menu item "Delete this node", then a confirmation popup is shown over the tree node).

**Comment by jusangdev** [comment]
I'm having this issue as well only manifesting when I right-click on unchecked nodes in the tree, then all nodes in the tree are checked. Would be nice if this gets fixed. Will try @davudk workaround.

**Comment by chrisch297** [comment]
Same issue here. Right-click on a leaf should not change the selection. Or it should be configurable whether a right-click should  change selection or not.

In my use case I have a tree with a context menu and the right-click should only show the context menu and not change the selection.

**Comment by javajohnHub** [comment]
Can this please be fixed soon?

**Comment by gcorsaro** [comment]
Any news on this bug? After one year nobody even gave a look. This is really quite important to solve.
The best would be to make it configurable so to have the possibility to choose if selection should be changed or not.

**Comment by Echtelion** [comment]
Same issue here.
A right click should not change the selection.
We also need a way to know on what TreeNode the context menu has been triggered.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by dmaf87** [comment]
Hi,
I guess there is still no improvements. is there any update?

**Comment by juanmanueldaza** [comment]
This issue has been closed without a fix?

**Comment by AlbaSS18** [comment]
Hello, I haven't seen this issue is solved in v16. Did someone solve with some fixes? Thanks in advance 😃

**Comment by Wyatth7** [comment]
This is still an issue in v17. The code below solved this issue in my case, although it is a bit of a hack.

For some context, I was attempting to use the built in `selectionChange` event to navigate to a new page every time the event was raised, but also needing to use the context menu on this tree. Obviously, if I want to right click to insert a new node a few levels up or down, I do not always want to navigate to said node's page (same as any file explorer). 

_Note that this will most likely need some tweaks if you're binding more than the context menu to the currently selected node. Again, I'm using the node from the `onNodeSelect` event for doing the actual work, navigation in my case.._

The `onNodeSelect` event below seems to only be raised on a left click event. Using this event instead of the `selectionChange` event in my case worked perfectly.

```
<p-tree
    [value]="explorerData"
    [contextMenu]="cm"
    (onNodeSelect)="selectionChanged($event)" // use this event to handle your selection event (do not use the built in selectionChange event)
    [(selection)]="selectedNode" // bind selected node for use with context menu, this is valid because the right clicked node gets set to the current selected node.
    selectionMode="single">
    <ng-template let-node pTemplate="default">
      <div class="node">
        <p>{{node.label}}</p>
      </div>
     </ng-template>
</p-tree>
<p-contextMenu #cm [model]="contextMenuItems" />
```
