### ISSUE TITLE
New Table  Filter Menu doesn't maintain "Match Any" 

### ISSUE THREAD

**Issue by rosenthalj** [primefaces/primeng#9651]
[x] bug report 

https://primefaces.org/primeng/showcase/#/table/filter

Angular version: 11.0.3

PrimeNG version: 11.0.0

When entering a compound table filter using "Match Any" option the selection is not remembered when the user tries to update the filter

Initial creation of compound table filter:

![CreatingInitialFilter](https://user-images.githubusercontent.com/45439491/102104973-cd477f80-3dfc-11eb-9c43-e0634258e41e.gif)

Closing and then re-opening filter:

![IncorrectFilter](https://user-images.githubusercontent.com/45439491/102105740-bfdec500-3dfd-11eb-81b4-fe00a101a899.gif)

**Comment by yigitfindikli** [comment]
Fixed in v11.3.0.

**Comment by fdlj-operanov** [comment]
Hi, 
strange, but in 11.4.3 with Mirage V11 the problem is still present. 
When I  change Match All to Match Any, the event.fiters for the column is at operator: "or", but when I re open filter by click on the icon filter for the column, it is alway display Match All . Ans if y change nothing in the menu, but just click to apply button, the event.filter the event.fiters for the column is still at operator: "or".
To change I need to chose Match Any, then chose Match All, then click to apply button. So the event.filters is refresh with the right operator : 'and'.

To resume:
first action: open filter menu
![image](https://user-images.githubusercontent.com/86430918/123312194-4a7c4b80-d528-11eb-8edf-371e0bf88f33.png)

==> event.filters (is ok)
![image](https://user-images.githubusercontent.com/86430918/123312300-70a1eb80-d528-11eb-9592-a68587f2356d.png)

re open filter (not right)
![image](https://user-images.githubusercontent.com/86430918/123312383-8d3e2380-d528-11eb-91a3-b07b21a2c6de.png)
