### ISSUE TITLE
p-messages inside a p-dialog dissapear when closing and reopening it (again)

### ISSUE THREAD

**Issue by saramcicchi** [primefaces/primeng#9698]
Note that this is reopening #8659

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Click a button to open a new dialog that contains p-messages. The first time, the messages show. When we close the dialog and open it again, messages are not visible.

**Expected behavior**
Message should still be visible upon reopening the dialog.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/primeng-message-not-showing-in-dialog

**What is the motivation / use case for changing the behavior?**
Messages should always be visible in a dialog

**Please tell us about your environment:**

* **Angular version:** 11.0.X

* **PrimeNG version:** 11.1.0-rc.1

* **Browser:** all

 
* **Language:** all

**Comment by theochiu2010** [comment]
Just hit the same issue, is anyone reviewing this already?

**Comment by cetincakiroglu** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by saramcicchi** [comment]
Hi @cetincakiroglu - this is still an issue in PrimeNG 14.2.1. It doesn't look I have the permission to reopen this issue. Can you please do so?

**Comment by sajimavelil** [comment]
Kindly give a solution for this

**Comment by godsonjarackel** [comment]
Issue still persists in PrimeNG 14.2.1. Please reopen the issue?

**Comment by juzeppe9000** [comment]
The issue still persists in PrimeNG 15.4.1

**Comment by mehmetcetin01140** [comment]
Hi, The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.

**Comment by chilinh12003** [comment]
Issue still persists in PrimeNG 19.0.0. Please reopen the issue?
