### ISSUE TITLE
Lazy loading modules that use pTemplate do not work without importing SharedModule

### ISSUE THREAD

**Issue by pete-mcwilliams** [primefaces/primeng#9782]
**I'm submitting a ...**  (check one with "x")
```
[ * ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
https://stackblitz.com/edit/github-fux54h?file=src/app/app.component.html

**Current behavior**
When lazy loading modules that use PrimeTemplate then they do not work unless they are importing SharedModule, or another module that exported SharedModule.

I've noticed this behaviour in MessageModule and OverlayPanel, but suspect any module that is using pTemplate will need to export ShareModule to work independently when lazy loading.

https://github.com/primefaces/primeng/issues/9033
https://github.com/primefaces/primeng/issues/9023

It was fixed for one module here:
https://github.com/primefaces/primeng/issues/8031

**Expected behavior**
Modules should be self contained.

**Minimal reproduction of the problem with instructions**
see plunker

**Please tell us about your environment:**
As it's reproducible in the plunker skipping the environment settings descriptions, but we are on latest prime, angular 11 etc.

**Comment by yigitfindikli** [comment]
Seems to be solved in v11.3.0.
Check example: https://stackblitz.com/edit/github-fux54h-n9es2j

**Comment by pete-mcwilliams** [comment]
Changed my blitz to use version 11.3.0 and the issue is resolved.  Thanks.

**Comment by rdhanasekar** [comment]
The same issue still exists in p-menubar. If I just use the p-menubar component with start and end templates, the templates are not rendered, only the menu is rendered. I guess the menubar module needs the same fix.
